#!/usr/bin/env python3
"""
BKOS Installer — Flash tool voor BKOS firmware
Detecteert MCU, downloadt firmware van GitHub en flashed via serieel of WiFi.
"""

import base64
import ctypes
import hashlib
import json
import os
import re
import shutil
import socket
import string
import subprocess
import sys
import tempfile
import threading
import time
import tkinter as tk
import tkinter.font as tkfont
import urllib.error
import urllib.request
from pathlib import Path
from tkinter import messagebox, scrolledtext, ttk
import io

# ─── Optionele imports ────────────────────────────────────────────────────

try:
    import serial.tools.list_ports as list_ports
    SERIAL_OK = True
except ImportError:
    SERIAL_OK = False
    list_ports = None

try:
    from zeroconf import ServiceBrowser, ServiceListener, Zeroconf
    MDNS_OK = True
except ImportError:
    MDNS_OK = False

# ─── Ingebedde afbeeldingen (PNG, base64) ───────────────────────────────

HEADER_LOGO_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAHgAAAAuCAYAAADjs904AAANsklEQVR4nO2ce3BdxX3HP78959x7"
    "9X7YsmUZJDAQjIlsZhjikEyrkgSSSWFaCOaVDjQ0tGDCIwTqEGLqYkIwECgUYtoEmACtSUUpIaQT"
    "MgXiZsrgGArCqTEUDFZty5as931I95yzv/5x7r2SjKwHYElW/J25etyzZ8+e/e7vsb/97QrTB2EF"
    "hvYmgY2wkRDQA5WtW1xXbYu8eWqD+UbcOqN2nqrUKswTtExhoSCeQpWgpYCiFCFSMWYrVHsRMoAo"
    "khToVtQX2KVIv0C7iO6xYtqtBrvFuHtNxm/fvW1311jtpQkHmmDeRqUZO0bZgwqZwmcZViC0Iwci"
    "84glR1Rb12kQdJEqixCOBY5CWQjUqGiliMREJGq65GsZVpVGzBYujtetQqGs5OscfnHYM1QVVc2K"
    "Sg/QgbALeB/lHRG2K7LdBOGOnVt3do36pCYc5qE0o4Adt8c+BhxMgnMSOjqhNUsaamMei7GcpGJP"
    "BlmscIwRqRIzvGNBNSJKtVCFzbE4/C1kxH/sd/XA2H8IaOH38CuCAAZAJGpfNNAYGktWsardAu+C"
    "bhM1r2J4PeuzrWPrjj0faNcQ4QdNwj9ugiNSAZoJh1+ob6xf5DvyaVG7HCvLEV0sxlTkOyknHdFr"
    "6ogBIbnOPRCBU43hA0AZ2U4nT/yI97K2F5VtGN2kYjZ5ob7cuqV1+4haV+AAfNxkfxydFY3sFYwg"
    "tWZJTannFC1H9AyQPwKWGcfEYQSZFs2pqiEJmW4CPyoi9ZuXf8EgmOGk29AOAi2gv0blV36Y2dSx"
    "tSNZqGEFDs1RUT4i2R+lMyMVs5Eg/0V9Y31VKHKawjmINonIESKSG8U6JJmzh8yJYjjpguCIiQjP"
    "DfadqGwUeMpRfbF1S2t34c4m3HEc0DHxYTrY0IQZRqxZuKyhSYULUT3LGFMLkT1S1UhCpUDm7wuh"
    "4yFS7bm+EREjJifd1u5B5OeibNjVsmMjeWcsItoySedsMh0e2decGl5w8oK5Enjni/J1jJwkIhGp"
    "VsNc6YJTcqgiL2FTgIJKFyOOmNxzrb6uwo/V9X/a9mrbPiCvviesuidGcDR6AoD5S+uPNsgVInqx"
    "MWZ+Tv0qSojgTLjOGQyTIzYIQzzPw9opmdHkUehLMSIigrV2r6o8atH1e99ofQ8YwclYGI8MQ06d"
    "zF+6aJ4rwV8rXGaMKS9I6zRKqohMbjQJ6Mjp1gfgGMPAYBYxQkVZKR1d3RTF40NToqmFRdG8VFtr"
    "+wR+FKh7x943trczZPYOOAIP3OqhESJ1y+pXAt81xtTa0IJqgMi0SauIYIyQ9QOCYNxBXIAqeJ6L"
    "Y0Yfj67r0Nefom5+DfetvoHFxy3iJ08+w90PP04iHp8qdT0aFNUQEdc4JrLTcOvultYfAjqWNI9G"
    "UMHWLvzkwqXqOPcZY5oiibXTSiyAMQbfD0hlMtTWzGHenOrhMZEx4RjD3n1d9CWTmP1Idl2H7t4+"
    "TjzuGB5Zt4ZjGo4klc5QXJTgzMuu4ZU3tlJSXDTV6np/KKqhGOPmJHqjhOHVu363640D2WZ3vwoi"
    "kW8mrGtsWKlGfyBiEjawQTSJl/3LTymMMWQGB6ksK+Xmqy7jjD84larysgmpzzAMqaoo5+pb7uSx"
    "p5+lqqKCMIz8wYjcfk7+5BIeWbeG2po5dHb34LkeWd9nMOtHz5g+Cc5DEHFVVTXQUBzTpA6b6hob"
    "vrW7eccPGTKVhYaaETfngm4Ll9WvN648gJLQ0IYILtPsPIkI2WyWmqpKfnrf7az8s/Ooqa6KJpjW"
    "Fj6qOqmGuq5LZ3cPTZ86mSfvv4O5VZX09iWJeR5lJcXc8vc/4o0336a4KIGdfoLzEARXQxuiJIwr"
    "DyxcVr8eCkH4Qhe4hRtyxnpBY/0GcZwLrB/6CG7OM552iEQ299brruTkE5fQ1r4Pz3UoLirCcUzh"
    "1cIwJDMwOCGpdh2H9s4uzv/jM7h39Q0IkEpnSCTixFyXlX/zfTY8+0uqK8qnWzWPjogbtYENjOdc"
    "vqCxvrJtS+uFDJPkSDIjm2sXNNZvcDyTJ9ebvpaPhBEhnRmg8fhj+cJnP8W+nh5inks8FuO1/9lG"
    "T38/ruMQhCFV5eUsOW4RYWg5EMcigmMMHV3dXHrun3DHqmsIgoBMNktJcRGD2SxXrL6NZ57fyNzK"
    "SoIwHL2imQFB8Kwf+o5nLljQWE/bltaL8py6eYeqrrH+duM5M45cADGGrJ/lhGOOpjiRoLOnlzkV"
    "FTzxi+e4cs3tJGLRNKYvmeTzn1lO8/3rSKUHRpXifEy4s6eXqy6+gFuvW0lvfxI/CCgtLqI/lebr"
    "N97CCy+/Qk111aS89GmF4Fnf+o7nXFDXWL9jd3Prt1mBE3nLyxpOE0dW2SAMcvZ2ViIXNKCvr59b"
    "rr2ctd+8gp6+fnw/yM15ezhn5fX85+bXmHcokZuH4NogDMSRVQuXNZxGM6ELGLW6zjgGVc0vzc0o"
    "qLXEvBhvvvse6YEBXNelL5Xi7DM+x6Ijj/iAii54vcNRCDsqd9z4Ta792lfZ19VDaEOqK8vZ+s57"
    "XPrtv+Xd1v+jqqIM/1AjN4KgiCBYa9cBn5YFy474UyPOv6lVywyOHRtjSKbS/Pj7N/OVL36ePfv2"
    "4bkuxUUJHGMKyzRBGDIwOHjAejq6uqmvqyWdGSAIQ6orynn9zbe5+PrV7OnopLy0ZKbb3InAihFj"
    "NTxbFjTWP2McOTNH8IzwmEeDiOD7PtVVlWy45zZOOnExXd09I7zb/Bxh/yDGcLiuQzbrAzC3uor/"
    "+K9NfG3VGgYGBylOJGYDuQChGDE21GelbumRbYipzemvGaee81BVPM+jP5XCMYbV37iM8758OvFY"
    "bFIhRNVo2SYRi/Gvzz3PTT94AN/3icdihDNxKvThoNFSmN1jQObnIjQzllyI5qz9qRRV5eVcftG5"
    "HNtw5IeKDUcRKXAcw/Mv/ZaOri5Kiotmi+TmIRGnMv+Q8JiNMaQyGT5xVAP/cOt3WHbC8Qxms6TS"
    "mSjcmHeoNPpzrCCH5n4OZn3uW30DPX39/HrTq1RVlBEEs4pkAGa8ihYRgjCgrKSEnz14N8cd1UBn"
    "Tw9GDEVF8cjB0nzZKGyZ9Uf3gFUV13VBlUHfpygeZzCb5ZyV19Oy7W0qy8pmiyQPqWhV2SwydXm6"
    "k0XkPWdY+dXzWHLsMXT29BDzPMpLS9jZtpet72znre3v89b299n6v9tp3b13VAm2qhQl4jzy5M/Y"
    "29lFWXEx6cwAiXicR+9ay/FHH0VfMoXrzFg/czKw0axQNrsY+zA4ZzEDpRcgCAKqK8s5/bPL6U+n"
    "cYyhKBHnroceY/0/NRfINCL0JVOcduop/PM93yOVHsCYoVdSaymKx3n1d2/y1K9e4Of/+HckEnGS"
    "6Qy1NXN56PabOe+qVezr7qEoHj/UHa5obcHYh01by85nNNTNxhiTy3qcMTAiZH2funk11NbMIZvN"
    "UlJczOtb3+Luhx4vrB5N1NkKraW6opzfvLSZa9behec6xDyX3r5+jj/6KB69ay2JeJxB3x9zqjWj"
    "oYTGGKOhbm5r2fmMIZoUr1I0ioNM0x6asWCMKSTAGREGs1lCa3HdKDvDDP+Ms4rkByGVc6p46pfP"
    "c91td1NeWhKtB/f1cdIJn+CRdWuipIIgGLeuGQiN/GdFjKwCrGEFzq6WHS9qqOuM67jo+IlcUwWr"
    "iue57OnYR0dXD7FYjGQ6zSlLT+SSc86kL5kklRkglc7kPmkyg9lx6w2CgLnVlTz+9L+z+p71VJSV"
    "4hhDV28fnzv1FO797vUEQYBVna5crA8HJTCu42qo63a17HiRFTguzVhW4Oxubr1xQWN9Q7RcaGfM"
    "ipLnenR0dfObV/6bv1hxNu2ZDL4fcNu3vsG5X/oCyVQ6UqcCYRBSWVE2eix6PwRhpK7v+8kG5lZX"
    "cu2fX0RnTy8dXd2c9+XTSabTXL32TqrKy4GxE/VmBBTfeMYL/fCJti2tN+ZTeFwobH6Sti2tFy5o"
    "rMfxhi34T7PzZa2lKJHg/sf+hS/94WeYW1lJbzKJG4acsnRJRO7Q7qBJLfhba5lTWcGaex+krKSY"
    "vzz/K+zt7KS9q5tLzjmL3v4kq+9ZT2V52cF9yY8GRQmM5+TJjRb8c/lZw3N4FDBtW1ov0jB80LjG"
    "I7LK0+p4qSqJWIwdu3bzVzd9j309PcybU00sFiOVGaA/maI/lfskU2QGBidsO5XIDJSXlvKdu+7n"
    "iV88R01VFapKd28fV19yIVddfAHJdHpmOl0RN2Jc42kYPti2pfUihqU6w8jVo/yXsqul9Qob6JUI"
    "A+IYJ2eXp01HhdZSXlrCS6+1cOZl1/JQ89Ps3tsO5BywYU6W5Cb1E0XecfNcl2vW3skLL/+W6ooK"
    "gjCku6+fm1ZeykknHE86MzCTnC5FCcQxDsKADfTKXS2tVzC06bbQBYdU2mw+KT0zOEBNdTW1c+dg"
    "zMQJHSttNkrH9XFdlyfvv4Plyxrp7e+nuLjokE6bPeQS36Ok94gMPwiYTHx1vMR3xxjSA4PMn1vN"
    "vatv4IRZmvg+HDN268qkt63AhLauGGMY/L3YujIchzefTeXjp3Tz2ciyh7ePHixM8/bRkTi8Afyj"
    "Y0ZuAP/gvYePcJgoDqkjHEar4/AhLEOYNYewjF7f4WOUZt0xSgeu+/BBaLPuILSxcPgow1l2lOH4"
    "zz58GOlBx/8Dc/QtJg2q2AkAAAAASUVORK5CYII="
)

ICON_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAABaRUlEQVR4nO2dd5xcZfX/P+d5njt1"
    "e5IlhBYgtE2hLCDWiV2/iIo6/ARFlAQUFEGwAcKyiKAgCDYwhiZ8RVkbiO2rYFa+Kl9gCUlgQXoL"
    "hJTtU+99nvP74967O9md2V5mN/ftayWEmTuzM/ec5/QDBAQEBAQEBAQEBAQEBAQEBAQEBMxpaKbf"
    "QMCU4H6vTd4/25OU9P7D1q1bCStLPGsdUF9fzwDQAgANLQwAaAZ7j+CizwuYtQQKYHZCaAKhPUkJ"
    "X6DXAa319YyWFoOpE1RCEyixLiF8JVLfXs8tDS3sKYlAQcwyAgVQ7jAoeUJSbG3YSlgHtK5sNWiG"
    "Ge4pjac3WnkZrVC5VJUTkhE4ppaAGBliDV5EAlaxKxCTYTKbSRBrppywaDs5Is9WqCujtqSf+cEz"
    "uRHeLSUSCYmVgWKYLQQKoLwgNDVRAutEfXs9t7S06GIPOuZLx0Rz3bl6Q2JPTbyYmBYTYTGDFoF5"
    "AQjzYFADIA5CmASBJAEMkKDS3zoDbFxZZQZYGzDDJoFeAL1g7gBoG4BXiOglhnnRML0gSb6I6uzW"
    "jVdvTBW7bDKZlFsbtlJr+5RbKAFjJFAAM4trUiMhPOEYIvCNpzfuntU4SAg6FMwNzDgEwL4ELCAp"
    "wkISQARXel0BZvb+7P0TAIPdPzGxAaPkN09Mov+9uf8Dkas03H8S3Ee4r8maoR1jE2EbM14SwJMQ"
    "9DgRb3Ty9MTjtzz88pAXaYIo+J0DhTCDBApg+qFkMikAYPAJ33h6Yyxv1CGCnCMZOIYNDgNhfyFF"
    "JUkBgF0B935gwEys+8WHQAQC2Bfdgdcc53vlgj/5CqRfmYA8hUEQvpVBggAQ2BgY26QBPE9EG8D8"
    "f1rQwxHix9vWtHUXvkgymZQA0HJniwEFymA6CRTAdOD58S0ACk/5xtMbLceIpQa8EuC3AjiKiPYS"
    "lnsIs3ZPWDauyAPuAQwmX8DL5ftzVQKxYe/PBBIQEEIKz+0gGMeAjdnCjPVC0P3M4u/xSrHhge89"
    "kOm/UhNEYl1CjCbWETBxyuUGmotQMjlU6I/6/FHzso55Cxn8FwMrielAEZIAM4w2YM3MzLrgdC0n"
    "QR8rDAb7bgeBJEki8pSCcTTY8AsA7ieiP0qt/7H+pvWv9j/bVwbrWnVgGUwNs/XGKl+SSZnEzuZ9"
    "wylHLbQsvNOQ+QgYCaHkPBKAcdgLtLEDApF7sothrj46RhKVYYKAIzLRO2ZAITCRqxCEdH9lbZtu"
    "Av+LBf1OOfov629a/6L/tH43IYgZTCqBApgcKJFIyNbWVsf/i0NPObTGRNT7YfAxYrxdWLIWAIxj"
    "YIzRYDDB9Z/H/GqDb/9+G4HceCAV/D0GAoT+H4cVH4GBxxY+139d38Yvdp3x3E0Mw8QGAAkSkpQA"
    "CcDkdR8E7mcjfsss7n7sxv973X9KIpFQgVUwOQQKYCI0QSTbk1R42i9fffRbIcyJYHxIKrEIAIxt"
    "YNhowPONx/K5F97ihIEovC+g7EYH2HUfYGwDdoxrXdhmwMpwGCD3vcDw0HfAAARBWMJNFyo3qCek"
    "AFkEoQTIEu4/VUHAryADAbNT5mHgPY8e97dx05VSKAkSgLb1DjD+SEr8t2XMfW1r2mzAtQq8WoMg"
    "VjBOAgUwHpJJiYYGRnOzAYDDPnPYAm2pE2D40yTEkUIJGFu7Jz3GKPQDEf0CYfcE3RNwk9PQWe8n"
    "p2Fy2hN8L2jIhSf0oJzfSO+CB/8L9VsYRJ7gS1dRiLCEDEuIiISKSIiwhAgJt+bAe89DlMIYVJ+v"
    "DIQQUlgCzAzjmHYiul3buL0/xegHWUvUTQSUJlAAY2DwibP89MblxPgsg06QlljgCSgzWBNIDkrF"
    "FadAMIjINcGJwNrA5A10xoGTdqBTDpyMA5MzMI6B+w7YFTT/IPaF1fvjpNPvCjDYVzDsKQkBkBKQ"
    "IQEZVVAx90fGFETYUwqAqxDMmBUCM9gQg0hJIZSAzjs9JOi3BvSTx9Y89G//gclkUgZxgtETKIBR"
    "4N1U/afLslWN7yZBZ4D5OBmSytgGRhvtpeFH9un9W1NgwIzWDJ3TsPtsOL02nJQNndGesBcK+sCJ"
    "XPSa00WJ1+8XbnbfMykBGZVQcQWrwoKqtCAjEiSFJ9aMfgN+NHcjwzDYkCAlLel+PsBfien6DWsf"
    "+q3/sEARjI5AAQxHMikLK9VWnHbkRxk4Uwh6BwmCzmsws0NEEiN9loOFHq4/7vQ5sLvzsHvz0GkH"
    "xmFXeAQNWASDr1HuFH4SfnmxJ+RkEWREwaqyEKoOQVVYECGv7sHAVXaDr1Ec1yoACWG55oXR5kEC"
    "fuJ0pW9vb2nPA0OVd8DOBAqgGE2e2Hmm/orTjvwogC+TFMcAgMlrw8Q8om9fTOhzBnZvHvnOHOwe"
    "Gzqn3Zte0NA6/dki8KPB/736FYJrIYiwgFUZQqg2DKvKtQ5AbhHUaC0DBmswSFpSkCRoWz8miK5R"
    "4Nu9gCEhmRTFSq13dQIFUMigYNKyVY3vFgLfEEq+jQ1D29qAwASSI1zHNdcFAYJg8hp2dx75jhzy"
    "3XmYvHtn9wf4CoRjl8H/nf2YAABhEayqEEJ1EYSqQxARNyPBuiCNORzsOiBCSSkUQdt6PYG+tfGn"
    "D/8aCLIGxQgUgEcikVB+Hn/FZxrfAIkLSIkPAoC2tSYGgWh4/57hnvZSgDXD6c0jtz2LfFceOuse"
    "Pq5SKHh8wFBlwICICISqwwjPj8CqskBKeFbBKFwEN07A0pLSqzj8B4O+uemnD/8N6P+uNYJvIFAA"
    "np+vAaDh5Ma9VZQuAOM0UkKYXL+pX/rE9+9H6Qq2yRrkOrLIbcvC7rMBw95/o50eH1CCQmWgGRCA"
    "iimE50cQnh+BjCj4XYgjWgVukRFLS0kv4HinNvqSx29c/wQQxAeAXVsBuLX6LS06kUiojgP7ziLQ"
    "N4Ql63TO8QNMIwu+cj9Cp89GdmsWuY4sTNYURPgRCP148WuMvJiBCEmEasOI1EdgVYUGYgUjKAIG"
    "a2IiGZbCaJMG4xqnK/2d9pb2vl3dLdglFUCh5l+6qnGlFHSVsOSRxtYw2jhEpEo+2ffvvQEb+e48"
    "slvSyHfmwdq46a3AxJ98CJ5VYABBCFWHEFkYRag2ApIEdszIioBZE5GUYQXt6KfYmK8/tvaR3wI7"
    "u4C7EruaAug/9Q88sXF+OE6XkqAziABt6+HTeQUnPhsg35lF9vUM8l15tx5HBqf9tOBbBdr9oK0q"
    "C5HdYgjPC7txgpEVATOzFkoqEgSj9S9F3vn6hls3vICmJgE0Y1eyBnYZBVB46i9f3fghIrpWWHKx"
    "zjrMYKbhAnw8YOrnduSQeTUFu8cGMPD3geBPM/7H7qULVYVCdFEM4flRkBiFa8AwAENGlDCO2Q7G"
    "1zb+9OGbgF0rNrBLKIBEU0K1Nrc6Dasa6iRFrxJKnMqGYZyRzX3/ZM935ZHZnHJPfN8F8B4TMIPs"
    "pAgYVnUI0d1jCM+LuDECp0jjUwHM7AgplFACxjF3OVn+YvttbS/tKpmCua0AmiD8qbRuTp9+JCx5"
    "gJOz9bC99wXpPKfPRvqVFHI7sjtZAnP7tpilFAQFQzUhxPaKw6oOA9orOS5tDTCDtQorpR2zlTTO"
    "3njTw78AsFOWaC4yZxVAgRknlq9uvIyEOB8AjKNLn/p+gE8JmLxG+pUUsq9nwJoDH3+24Otn7+SP"
    "1EcR2zMOGVUjxgeYWQsppGsN6J8iY39p4+0bU74FOW2/wzQyJxWAH9E96JRDF4cs6yYZkm/XWe/b"
    "L+Xr84BZn92WQfrlFHTGASkRCP5sxA8WOgYiJBHbM47IwihI0PBugTexSIUtaWy9QTvOKY/f/OiG"
    "udpcNNcUQH/N9/LVjR8C0RqpRL2Tc0Y89YUSsPtspF7sRb4jD0gvjz+nvu5dkIL0oVUVQnyfClg1"
    "YTedaDCcNeBISyrDnCLDZ29c23YjAHcj0xzKEswdBVDgq61YfWQTKbqENbttulSioIf9tB4jszmN"
    "9OaUa+6rQPDnHH5AUADRhTHE9qqAUMNbAwyvbiAkofP6+k1Pt30RrXDmUpZgTigA3+Rf8omjq6JR"
    "fZMMqY/qnKPhzscfavIXnPr5njxSz/ci35OHCMz9uY333RrHQMUtVCyuRKguPHxswHUJtIpYyuSd"
    "f2g7+8nHb3n85bkSF5j1CsD/Ig4+ecWBoWioRSi5wsnaw5r8vq+f3pxC+uUUmLm/si9gF8DPFgCI"
    "LXKtARLk/t0wLoEKK2U0v8w5fcKmWx95YC4ogVmtAPwvYNlnDkuQUncKSfU6P3yUnywBnXHQ92wP"
    "8p25IMi3q1JgDViVIVQuqYKqsMC2GVYJCCUVCGnW5pRNa9t+NdvrBSY+g36G8IV/+arGk4Rl/Q8R"
    "6nVe6+EKe8gSyO3IomtTB/JdeZC3gWd2fnUBE8L7zoXl1np0bepAdksaZJWu8yAiZRxtWHNMKNGy"
    "7NTGc1tbWx1v1dusPExn45vun8G/7NTGc2VIXm0czWxKlPPyQFde6qU+pF9JuYM4ggh/gE9/ypAR"
    "WRhFxb6Vw7sEDIaAkSEldd65etPati+jCQKXgGfbroLZZgFQU1MTtba2OstWNV6pwvJq42gNA5QU"
    "fuXupOtu70Tq5b6CkdUz8O4DyhO/0csiZLek0fVYh1sDYpW4TwgEhnBytiND6rzlqxt/hma4i02b"
    "ZpdMzR4LgEG4xM3BLlt95DUqLL/kZG3H69kf+nt4/r7dnUfv093QWR2k9wJGxksXCkugYkkVwvMi"
    "I8YFrKilnJzzC92dOaW9pT3vlaDPilqB2aEACoR/xaojfy4j8kQ749hEsEo8HmQJZLdm0PdsD9gE"
    "Uf6AMUCAO1QMqFhciegeMbdeoATMsFVEWTqv/x4S/IG2NW3p2aIEZoMC6K++Wr6q8Q4VUR8fVvjh"
    "pvnSL6eQeqkvqOEPmBDsGEQXxVGxb6W74ahE9WCBElgXEnzsbFEC5e6vUDKZFKMS/oJJvH3P9iD1"
    "Ym/QshswYcgSyLyaQs9/ugZqSIpmCGA5WduRIbkyb+gPjac3xtBc/jGBcrYA+qf3LFt1xB1WxBpW"
    "+EkQmBm9T3cjtz3rpvgCwQ+YDAhg28CqDqHqoBoIS5TMEDCzoyKW0nm9LhPtet8zdc+4k2PK1BIo"
    "V+1EiaaEdIW/8XsjCr906/m7n+gKhD9g8ukPKNvobu+EzuthLAFSTtaxZViujGaqb0MzTLI9SSjT"
    "w7Ys39RAhd/hV1qx0FdGEn6TN+h+ohNOygki/QFTh1dCLEMSVYfUQMVVyWYiZthWVFl2xvn5Yze1"
    "faJc24nLTgE0nt5ota1ps5evOvxLMmxd4+Qch1Ckus8XftvN8QfCHzAteEpAWALVDbUjKgEVVZbO"
    "2tdsuvGR88qxd6CsXIBEU0K1rWmzl556+MdlyLpG57VTdDZ/ofA/Hgh/wDQyhoPHDwyqiHXu0lOP"
    "+HJrc6uTaEqUnkE5A5SNBeD3WDd8pvEtKiTuY2MENARo0HsMzP6AcmD0lgAD0MKSysnaH3/8lvW/"
    "LCdLoDwUgJcvbVh1+BIp5b8ImG8cM7S2n+HW8BtG12MdgfAHzCy+EggJ1CyrgwzL4tkBBkPCEJFj"
    "HP32x25a/+9yGSpSDgqA0AQ66OWD4iGq+LewxFKvq2+o6e8V9HQ/0QW7Ox8If8DM45UOq7hCdUNt"
    "yRQhMxuhhADz69qmox6/5eGXy6FQaKZjAJRoSkg0w4So4lYZVku9fv6iI7yICL1Pd8PuygXCH1Ae"
    "eA1nTp+Dnie73PHjRaSKiIRxjBZK7iaE+VVDsiFUDunBGVUAiaaEbG1udZadekSTjKjjS07y8fz+"
    "3ud6gjx/QPnBbieh3WOj56luEBWXaSKSTs5xZNQ6WlZFrm9padGJpkTpBbTTwIxpH98HWnZq47Ey"
    "JO8xtnYADO3s84ow0i/1ueW9gfAHlCtexWBk9xgq968aJj3oVgs6WeeMx25qu2Emg4IzowC8jT3L"
    "Vx+9B6AfJaJaz28aEvTzu/p6n+oeqO0PCChXPCUQ37cSsT0rSrUSMwiGBGk4OGbjTQ+vn6mg4Ey4"
    "AJRYlxBggFn/t7TkPKMNFxV+RbC78+h7ticQ/oDZAbubpVIv9HnuatFYFbFhIqIQE/+i4cyGCv/v"
    "p/fNzoAC8Md5LT318G9ZEfU2b2nHUD9IACZv0Pt09/B73QICyhAShN5nuuH0OUX7BohIaFs7MqwO"
    "lJnoDTMVD5hWBZBMJj3hb3y7CqnznWwJ4QcAL+Kvs6UbLwICyhZvRXnv091uWrB4ZkA5WduRUfmJ"
    "pZ857FOtza1OMpmcViUwfecqg3ACxKGxQyuNpdaTEPsYRxct9iFLIPVCL9Iv9wVBv4DZCwFsMyL1"
    "EVQeWF08KMhgEsQM9ArbPmzDrRtenM71Y9NmASRWJiRaoLVQ35Nhtdg4WhcXfkJue9ad3qsC4Q+Y"
    "xXj3c3ZrBpnX0sUPMwIZY1haolpLdSMATqxLTJtcTssL+ab/slMbj5Vh+elS+X6SBJ3R6Huuxx3l"
    "HRAw2/GDgi/2we4pXr3q1weoiHrH0lOPONPbNTAtrsDUS5k3EunQFw6tMpZ6jAQtYoeHRv3hBk66"
    "2zvdpR1BpV/AXMHrGVAxhZpldaWkjiHIEJBhB4duuvnh56fDFZhyCyC5NElohnGE/LYMqT2MY3Tx"
    "lJ9AenMK+c5A+APmGF4lq9Nnu4Nqi7u2xNpAKFHBMD8CwF6p8JQypS/gFzcsXdX4ZinF/7I2Gq7S"
    "GXhdP9/fa6P7sc4g3Rcwd/Eah6oOrkF4fhhsF20a0iqspJ23P/74jet/OdUFQlNpARDgDvkQjB+7"
    "y3i4/+8LH8WG0fd8b5DvD5jbeJOrUy/0wuRM8dQgiIxjjID4XuPpjdUtDS2lFpdPClOmAPyJvttf"
    "7v28jKgV2tZ6yHQfz/TPbE7DKREgCQiYS/iB7v41dUOzAsJowzKsds/ZphnNMN7y0al5P1NyVS/w"
    "17DtqHqZ4yeJUMnMQ1ofSRCctIOuTR1T8jYC5iZEBCF8mfAOSGYYY2bN+cGGUX1ILUK1oWL1AW6v"
    "ABEz8RGb1rQ95h+ok/0+pkSzJNvdwJ/I6stkWFYbY0rsUwFSL/aW3sIaEFAAEUFKiXzeRkdXNzq6"
    "utHZ3YuOrm509/bBMEPKmR5xMQq8e32Ye5+YGUIJBYevxhTaxZMudn7Q4tDVhx7GZLUxs7tMeXDg"
    "zyJkX8+g96me0ltYAwI8BBG0MejpS+HAfffGW486AgfvtxjRSATbOjqw/vEncf9D69HTl0J1ZQW0"
    "Kcs9HAP4XYP7VCK2d/GuQQZrFVLSyekPPHZT2x+mIiA4ZRNKtZGXq7AQTs7RNHhCggBMziD9csqN"
    "CgTCHzAMQgjkbRtKSlx6zhk46bj3YcG8WjADAIOIoLVG+zPP47trb8Pd97aiurICppyVgJ/6fjWF"
    "8LwIRFQCZqggsGEm4PKGZMNfWxpaHEzypstJtZf6h3ycdlhChuT7dd4ZOtuPAZLuL64z2h3yGRBQ"
    "AikE8vk8LKVwy5XNOHf1yQiHQ9jR1Y3O7m50dvf0uwAHLN4bt1zZjDM+8TF09/ZCijJ3B7xegdTL"
    "faAiYk0gqW1tZEStUBXRj6MZZrI7Bif1E2ppaGAwiBxxBeAp6EH4BRHZLZkg6h8wLFII5PJ5WJaF"
    "W69qxjveeBRe37odxhgoKSEH/aSzWXT19OLy876A5Pvfja7evvKOCfi9LzuyJQvgvLQgs+CmFZ9c"
    "EW9Fa8l42niYtE8nmUxKNDeb5ac1flBG1Bu1rU2xtB8ISL/SV3JcUkAAMFj4L8XKo4/E9s4uWJYq"
    "OXPPPfEZ6WwOX/vspzG/rga27ZR8fNnAnkwUE22CMI42MmLtp0Nq9WRbAZOmAFoaWhgMYoOL2RQ5"
    "/L2Kv3xnHrkds3eqLxFBeGkoOUd+yo2hwt+I7V1dsNTIISshBDKZLPbfe0+8721vQl86XZAyLEP6"
    "J1/ZyG0rbhUTiIytmUBfWfHJFfHW5laNSTo+JyUImEi4Qw2Xb278kAzLI5y8M7ToxyPzWqrfEpgN"
    "CmAg58zQ2sC2HThGQ2s9K97/aIhGIxBlckpORPh9iABmxhtWLMVtv/3DFL7bSYIBCCDzWhrh+ZES"
    "VoDRKmLtYYNXA7husgaJTooCaF3ZatAKsMF5zEXEwtNyuR25WdPsI6UAM5DN5ZDN5QAQKuMxzK+r"
    "QW1VJepqqqGULB7omGVsfPJppDMZSCFm9GuZDOEHAHgpw4UL5sNSCsxlnA3wcGNjDrKvZxDdIzak"
    "T4BAxI5hATqrIdlwfWtzq41JOEYnrACSyaRsaW7Ry047MiEFvdXktRkS+SeADZB5NTXRl5typJRw"
    "HI2u7l5IKbH/PnviTUcciqOWN+Cg/RZjt/nzUBmPIRwKQcyRDMa7TzkTTz77PFQ4DJ4hjTZpwl9A"
    "3rZn7PcZM+xWxma2pBFeEB2aHicI7Witwmp/4ujHAfxsMqyAyasDcMx5FFFgsCEUTPrxT//tOdg9"
    "dtme/kIIgBmd3T2orqzAR973TnzkPe/AGw5bhnk1NQAYeduB7TjQWiOby3k31+xXAjMtJJMt/MwM"
    "JRWefekV2I4Dd/DUjK/hGxkJ6LRGbltxK8CteGY24HPQhNu9jMCEmJgCaIJoaW7RS1cdfggRvV/n"
    "NRc7/cFAdmt6Qi81lSgp0ZfOAGCcdNz78NmTPoblBy4BMyOVyaCzuxsAQCRA5MYF/J+AiTEVJz+B"
    "kLfz+PsDD0MpWSIhXYZ4sYDs1gwiu0WHnC0EkiavjQzLw5e/fPjbN920/t6JVgdOKDzqDywgiC/I"
    "kFLMvHN00huEkO/Ku1N+ymy6LxFBCoEdXd04eP/FuOPaK/Cj5q/j4H33QVdPD7r7/PpyN88sRCD0"
    "k8lUCL/tOKirqcK6/2vD/Q+tR2U8Vv5lwQX4sYDc9mxRa5m9JiFD4kuT8XoTUQDU0tKil5+xvJaA"
    "E42tUWrEd/b19EDkv0wgIjAzunp7ccpHPoC7bvgeVr7hSHR09yCdzbpCL0Q5veU5hZQCubw9qcLv"
    "aI3KeBwvvboF37jmR24RUBkdOKOGXCugWKMQgaTOawjCe1esXnFgS0uL9rtvx8O4n9hfjJCzTpRh"
    "WWvcaT87t/t62izfWV6nvyCCMQbZXA6Xnft5/ODir0FKge7eXigpyztvPAeQUiKTzUEpOanCXxGL"
    "YuuODpz0pQvw3EubEQ2HUawkpazx6wJ6bNjFrWZiZi1DUhm2TgOAiUwRHvcTWy9p1WiCYOC0oi2N"
    "Bf5MObX7EhEMuwG9HzR9DV885URs7+qCMQZSzuii1l0CJSVSmQzqaqpxx7VX4G1HHYEdXd2TJPyd"
    "OPGc89H+zPOoqojPKtO/GNmtmaJ/TyBhHANi/uSKT66It7a2+k1CY2ZcCiCZTEoQeOmrhx0jlTzM"
    "2GZo2a8ATNYg15Etq9OfiNCXTuO755+Dk457P17fvgNKysC3nwb8YGt9XS1+ed238aYjVqCzu9sN"
    "1I2TYsJfU1UBR8+CqH8pCmJnTsoZuhfTnRqkZVgtREgeB4DGWx48LgWwdetWAgBhxMmkCIxBlRbe"
    "L5DryMJki88+mwmUlOjo6sZ5q07GKccfh607OiZ08gSMnn7hn1eLO669Ag1L9sWOrm6oST75a6oq"
    "4DizWPh9vAGiuW0ZV36KHKAMsGE6BQCPNyU4HtGk1tZW56BT31TJTB81thka/COANZDbli0b4ZdS"
    "oqu3F+9925vwldM+hY7ubsgJnDwBo6eY8Hf19E262T9nhB8YOER35GDyQw9RAglja5Cgdxz62UMX"
    "oxlmPMHAMT/BMzUojMyxKiwXGGOKpv6cXht2n+1u+Jlh85+IkLdtzK+txbe/cha0NmDmcglLzGlK"
    "Cf+UmP1zRfh9BKCzunQw0LCWYRXSefVxAEhg7MHAMT+hvr2eATCT+H9wJ30XWXEA5LZngEntXB4/"
    "Ugj0pdI4+9MnYsk+eyGdyQSR/mkgEP7JIbs9W/wQJRAbAyJ8DAC8LsExMVYpoJaWFt14euN8ML/D"
    "OIaGmP8CMHlTNoU/ggipTAaHHnIgTv7wsejq6Z2Q3wkAxhhoreFM0o9/rbIeYTVGAuGfBLz+ALsn"
    "D53WwKCPznUDDEPg8MM+e1gDAB6rGzAmSUg0JWRrc6uTc/i9KqyqhrT9+j3/HTnorC6Lun/yqs1O"
    "/diHUBmPo6O7G2qc6T6tDaQUiMeiCFkWqL8Za2JmDoMhiJDL20hlMrM+IxEI/yQi3LFh+a4covHY"
    "4JQ6MbOjwpays/xhAO0JJMRYAoJjUgCe+Q8i+hh8879I/j/XkZtxwQdc3z+Xy2GfPRbhvW99I1Lp"
    "9LgGYDAzmIGaqkqkMxk8vOkJPP70M9jW0QVBNOFfVRAhk8vh0IMPxPsTb0Imm5u1Lkog/FMAuTIV"
    "3T1WbFYAsTEQoI8AuGKsbsBYFAC1tLToQ88+tEb3YmVJ8z9nYHeXifkvBFKZLE568xuwe/18dHR1"
    "j7nYxxgDpRQi4RDuuOfPuPHO3+HJZ19AKjNQpFEsDDIWlFTo6erCKSccj+Pf83akM9kJXW+mmCrh"
    "r4rHsWX7jl1T+AsWizopByqu3BV6Hp4bABAOX7H6qAM2rn3oKTRBjHar8KgVQPLOpGg5oUWbXvE2"
    "GZI12i5t/pu8KQvzn5kRsiy8+y3HuIUhYzStDTMsy0I+b+Ocb16FX/35bwiHQohGIqgLVwOYnBin"
    "kBKCgIpYbMZbc8fLVAr/C5tfxae/egmefHYXE34fb3qw3ZOHqlRuZ/NgNyCilJOz3wPg6bG4AaNW"
    "AFt/tNV7SXEsidLmf76zfMz/fD6PPXZbgBUHHYDsGM1qhmuagxmnXfhN/Pkf/8Ju8+fBGNMfBJws"
    "JDCrg4BTIvyORk1VBdqfeR4nnnM+tmzfgerKXVD4fciVrZJuAANgcSyAH44lBjBaiaDW1lan8fRG"
    "C+B3scO009AP70rGNu7Qj3Iw/72g2gH77oN5tdWwHT2m09pojaqKCly19mf48z/+hd0XzIfjOLNW"
    "SKeK6RD+rTs6UBWPz+7y3onguQF2nw2d1UWLgtgxIOI3H/z5o+Z55v+obvfRKYAm92JZWzeQEPsa"
    "bdgLgQ+8QeF2/umcLovcPxHB0Q4OWLw3QpYFM4a5cIYZsWgUG598CjfeeRfm1VYjb9tT+G5nJ9Mj"
    "/J2oiMV2XeH3KXADihTXEWs2wpKVKmOOAdzt3KO57Kge5FcYCYi3i5CgIYM/AIAIdnfOXW9UBgrA"
    "hbD37rsBTGM7/Y1BNBzG7/66Dj2pvnGnDecy0yf80UD4C8h350v0BbAhIRiEdwHA1oatk2cBtLa3"
    "MgAYQW/zXnyQ8APQDLvX9mYyj+aqUwvDneSzoK52TKc/4FYOprIZPPDoJoStEIwOzP5CAuGfAQqy"
    "AWxzcTfAGCLgLcDoqwJHowAILdD7nJKIEONoow2KLfvUOQ0n47jmSRnAzJBCuEsi2Yw6A+AOlJTo"
    "6unFa1u3wbJkOeizsiEQ/hmEhpEzArHDALDs0M8eugf6J3IMz8gKwPP/q6zepULSHqx55wv75Yq9"
    "xTXTTDOetBoRwXE0bGfccxbmJIHwzzC+pd2TL7YRgAwbLUMyom11FAAk70yOePOOKK6+/8/MRwpL"
    "gMFFvxmnzy4L038wY43akzcuLBqJIB6LwhgTqAAEwl82EA3I2tA0PMOtTD0aALY+PnIcYOTzel3/"
    "Q4/xXmTQGwKgGU7KLqt1X0QCtuNge2cXpBjbaGhHa9RWVWDJPnvDtu1ZX5s/UQLhLxPc4hQ4aWfo"
    "zgDAKwtmEPAGABhNPcBICoBaW91gAgGHs2YMyf8ToPMGOqPLxv8H3M/GsMHrOzrGXK/vL5Z415uO"
    "hq01aJbW5U8GgfCXF0Ruub2THbr12AsEAsCyFZ9cER9NPcBo7mxe8bkV9cxY4nUiDcn/64yGcUxZ"
    "uct+Jd/zL78Kw2Mz44WU6E2lcNw73oaD9l28y84PCIS/DCGANUOnnKKjwlgzC0H1whJLAPTH8Eox"
    "7F3tFxOQbTVIS8TZFNlgTuSa/2WV/wfYGFjKwn+efwHpTBZCjP6mJQC2o1FXU41LvvhZ5PLujrld"
    "SQkoKdGbTgfCX6Y46aKFacRgLSwBm2gFMPKUoGH/o19M4DAfSlIMHf4JAMxw0uUXLWdmhMMhPPfS"
    "ZryyZSvCITWmjIC7J6AP70+8GZedeya6e3uRy+ehlIIQYk7HBZRnAS2qXxAIfzlCcGWumIHPAIhA"
    "wBGjudTwR9o67/WIlhaN7vnmSKa4OTKTMABLKWzv7MQDj25EJBwZc0bAXxZyxklJ3PSdS7Cgrhbb"
    "OjqRSmfm7I2rlERXbx8O2m8x7rrhGhy032J09QbCXzb4bndWw2sD3hkvEAiIQ4CRA4HDKoDWld6T"
    "GQd7xv+QCkBjG5icKc8T0TPb/9T6Lzh6aNBkNAgh0NXbiw+/ayX+eOP3cckXP4ujVjSgMh4DMOYO"
    "47JGKYWunj40LNkXd1x7BRbVL0BvKjWhUuhA+KcAry9A5/TQQCATwR14uySZhBwpEDjc7UsAeMlZ"
    "S8KRVPUzUok9jTYD2Ud/hVG3ja72jvJUAAXc89PrcOC++yCTy7ltvmNEa4NQyEJlLIZUJoMt23eg"
    "p7dv0n5vbQyqKypQP79u2jsOjzv9HDz74svI5e3+Jan182rRl84Ewl+OeDsDqg6sRrg+Mjgl6Dbq"
    "GeSE5ey/4ScbNnt/U9Q+Lz0PoAmEZnBlqnKhDexW9KYkQGcdd0CBhbJyAXyUlNjR1Y1f/uF/cPmX"
    "v4BUOgMxDnNWSgHHcbCjqwtCCCycPw977LZg0jZPE7lKxq0+nF4sJdHV04fGZQfjv793eSD8swFm"
    "OBkH4aHFNwQDJkVho+VeADYnT0iKFhRfIV5SASTbk9SCFmgl9pIQlnEGtQB7r6WzGmW3+rcArTUq"
    "K+L4xR/+gk8d/wHsvWghsvn8uKwAIuofKZa3bfBkdgizqwSm25ISQqCzpxcNB7hm//y6mkD4ZwUE"
    "k/Nlb2eYWEsplda8H4AHhusMLBkD8J+kHbMvKQJTkRJgdv2QchV+YCAYuKOzG1ffeJu7MXYSTGwi"
    "gpjMH0EzIvyZbA4rDjoAP//e5aifXxcI/2zBawxCMfHzMgEGZt+RLjNyYpuwt+t0DH0DMHC1UJll"
    "AAajtUZNVSV+85f7cNe961BXXb3rjpYqwO2YJFz19XOw58Ld0JtKB8I/G/AMbpM37pjwEg8iFosB"
    "FJTzD6W0AvCeRBD7lJJu1uymImYBzIxQyML5V/0Qz7+yGfFYdNavj54o7A09DYdCyObz4xqZ7hMI"
    "//RCgmAc41bgDv7aCORV7OwFFGTzilDyG2+td4eAELCIXY0zNAWoDdjhss8AAF5hUCiE13fswBcu"
    "+Q5sx4Gl1C4/44+ZYYwZV0zEx3acQPhnAg0YxwwVTT8VSFgIAMOlAkspAMKd/lxx3q3YhHEigrHN"
    "4E0lZY3WGtUVFfhn26M4+9IrEQ5ZUErt8pbARBS442jUVVcHwj8DsGF3c3CR2QBwl9nMW3LWkvBw"
    "1yht8xG48fRGi0ELwOxqlf5XRn8ucrbNsXe0xryaavz6L/fijIuvgCBCNBwObthxYDsO6mqqcf/D"
    "6/HRz38F2zo6EQ+Ef3rwhJ6LNeER/KL92pCurR3uMsM6fU7UiROjkpmLugBsm7LZADwWXCVQg1/9"
    "6W848Zzzsa2jE7VVVXC0nnUKbaawHQfza2rQ+mAbPvXli9DT14dYNDqp+xICRsKPwQ0VQHZdgLjq"
    "RRWAkl2BxRWA92DRK6oBxEsJhXFmr+nsWwL/bNuAD5x2Nv7nf/+N+bU1sCwVKIIR8IV/3YNtOOUr"
    "F8O2HUTD4UD4Z4ASQXgCg0kQOKzrALeup9gDh7cAICMghIsnAchTALNXUBytUVVZgW0dnfjUly/C"
    "2d+8Cts6ujC/tgYhy4LWBtqYQBkUMFT4bYRD1i4fR5kZyEsDFr0/mQSBgNhwVyiqAPq1hTC13hKC"
    "IqV+7L34LLP/B6G1RtiyEI1EcPOv7sZ/rToLV9xwM17bth211ZWorapEyLIADGwJ3lUpLvyhQPhn"
    "Cq8bt+ieAGLXAgDVAaX3BAy/G5BMBQkJbxLwkAuULkKYXRhPqufX1qAvlcaVa27FLb+6G287+gi8"
    "5y3H4LCGg1z3QLkzBXbFG14bg/q6Otz3wIM45StNgfCXCaxNqUp8doOBpmq45w+rAIjFnP92idyS"
    "WDCQzmaRy+cBELZ3duGuv7XiX49sQMOS/fDGw1eg4YD9sN9ee6J+3rCB1TmHYUYsEsY9f78fn7/k"
    "24HwzyIINOyXVFQB+OaCMdhdhQjssNlpGOhwKYhZAhFBCLfDr6evFwTC3osW4vClB6Nx6SFoOGA/"
    "7LPH7qitrgIRgZnhOBqyjAafThf+mvX7/v0gtmzbjj0X1iOby8+KArA5y0ipeK+MzwCLhrvM8C4A"
    "c2i4N+BOHpl9SClh2za6enoxv7YGH33vO3Hs29+Kow9dhoUL5kEK4S0GseE4ut/FsqS7JWhXCwoK"
    "IdCbSuOyc8/EK1u24s//+CfqamrgzEDrcsDOsCkeAxh4wDAyjJFcAKI5dacLIcDM6OzuxvzaWpzy"
    "keNw8vHH4sDFewNwXYDu3j64ZZR+dx71T/2ZUx/GGHBHrDOMYXz/4q/gI2e+jiefewGV8XiQ+itz"
    "RpLh4S2AOYSSEqlMFsyMk4//AM46+eM4cN+9kcnm0NXTBwAQgibUEDOXEUTI5nKoqazE2isuxvGf"
    "Ow9dvb0Ih0K7fD/FbGaXuNuVlOjo7sY+eyzE7ddchh9c/FXstXs9dnR1I5fPQ0oBKef2pN/JQHqj"
    "wg9cvDd+ctmFEETQeuhcuoDZw5xWAH6gb0dXN45/zzvw+zXX4V1vOho7urqRzdtQUgY37xhxlWkP"
    "Ekc34rvnn4tUJjOnBqPuagyrAJh51n61vmD39PXh65/9NNZecTHisSg6e3qhpJxQ++uujqUUtnd1"
    "4aQPvg/nf+5UdHT1TGiQSMDUMZIMj7A1RAwf4SlTGfKFv7u3D81nfw7f+MJp6Ontg+04wY06SSgp"
    "0dHVjfNWfRInH38stnd2QaldJqRUPowggzSCDBdVAPXt9QwArPSrrBnEgxaCsvtMYcmyDI0TEXpT"
    "KXzzS2fg7FNOxNYdHSAhglN/kiEi9KUzuOpr5+Adbzoand3dE1ogEjAGvFocYYniS3kJ7gPIbB7u"
    "MsPHAPTsSwMqKdHZ3YMvfeYTOOczn8C2zi7X15/pN1bGmHHWc5AXBASAGy69AAfvvy96+1L9k5MD"
    "ygAe/oge3gUgkfWKXorKTzmtAwc84e/pwQfe8Vacf8ap2N7RGaT1RoCIEI2E+/shxooQAtlcDnU1"
    "1bjx8otRV1ONXC63Sy1SnUlIUCk3gMCAIGSGe37Rb6mloYUBwDBtL1gJPugOIZAq8tczhCBCJpvF"
    "4j0W4cqvnY1cLu8uSQzM/pJIIZBKZ/D3Bx5CRXT8Q1KllOjtS+GQJfviR83ne0VDZboubi7BAClR"
    "bCQYiMndEShoKzDg1g9mWDVNQuSZYRfXMAySbqVcWUAE29G49JwzsKh+wbiXfwzGMLtzAbSGM0U/"
    "/rWnu6DGMCMaCeOS7/8Ed9/Xink11eMu71XKDQq++81vwLe/+kX0plKBAphyhpdBdkf55Ya7QvGw"
    "bbOrT9jKdFEu1EdEtcXq34VVHmaelBJdPT34yHvegQ+8463o6J5YWqp/Uq4QiIXDsEIWBFGBITS5"
    "NzaDIYiQy9teXn16BIe95alKSpzVfCX223NPLD9oCbr7+sb1+SmlsL2zC5/56Afxymuv48o1t2J+"
    "bU0wI3AKca3wITAIgjWDmbYDA1b9YIbN22RUJh3NW31EopaZd14NxnB37JXBUhCtNSrjcZz96ROR"
    "y9sTOvm11rAsCzVVlUhnsnji2efx9IsvY/OWrUhnsxBUYsviBBBEyORyOPTgA/H+xJuQyU6fD+13"
    "+qXSGZx24aX4zY+vxoK6WmRyuXHFT9z0YA/O/9ypeHnL6/jF7/+CebVB49DUQJCWRDEBJCIYYzLS"
    "ctw69+axLgcF6JkfPJNbtqpxG8hdMFDwuq7/Yc28jy29qP+njj8Wyw86EB3d3eM6vZgZhhk11VXY"
    "0dmFn/32Htx9byuefOZ59KTSMMYUDEaaXBWgpEJPVxdOOeF4HP+etyOdyU7q9UdCG4N4LIoXXnkN"
    "p134Tdz5/e/AkgqO0ePcoQikMhlcff65eOW11/HvRzaipqoysAQmE+9WJCWK344CAFNnNBbtGO4y"
    "pRQAowkCzWAwtoLIHTG0kwHAEEoAEii2N2C60EYjHovilI8ch7xtQ4wjM8Fe9191RRy/uOcvuObG"
    "2/D0Cy8jZFmIRsKoqaxwA4pT8P4BQEgJQUBFLDZjrcb++rR/r9+IL33raqz51jfQm0qPy+Hx04NK"
    "Kfzksgvx4c+dh5de3YJ4NBIMEZlMBCBCRRQAg4mIANPxwPceGHsWAAAS6xICAAh4jVwzf+eXYdf/"
    "ELKEBpoG/Cj2Gw9fgeUHLUE6k4GgsZmt7n48gZBl4cuXfw9nXHQ5XtmyFfNqqhGPRQG4J+RcDAIO"
    "xvFm/v3qT3/DZT9ai7rqqnG3+7qLR7PYbf48rL3iYlTGY8jZdpAenERI0EAcrkBLM7kzwQF6HQDQ"
    "VNpRL/1trPQuBn6x6BnAAEn3DczYgAwiOI7Gf618M0LKGnMum+Ge/EopfPGbV2HNL3+DeTXViIRD"
    "ZSGQM4E/Lv3am3+Otb/8rRvEG+ciVSUlenpTOPTgA/Cj5q9De5/pTLuNcwIGhBIgRUPlj+HX7r4M"
    "DBzmxRhRHRPwoivtRf6bIIiwnJHlIATAdmzUz6vDWxsPRzqbHXPQymhGZTyOi6+7AT+/+49YOH+e"
    "J/jlUdswUxhmVFXEccHVP8SfWv+Jupqq8SsBLz34/sSbcfl5X0BPXyooyZ4EmBkiJIaxwAlgfgFA"
    "/2FejJIS4xcOCKIXSvYDEEGEZyYNIIRANptHwwH7Ye89FiKXt8d0smitUV1Vgbv+tg4//cVvUD9v"
    "HuwgUg1gID0opcTnm76Njf95GlUV8XEH8fz04Or/dzzO/vSJXuNQUC48bgiAgXv4FhM/rw9AMD0/"
    "0qVKKoD+akBDL2lHa1Cxl2LIiMS0H/9wA022Y+OwQw50p9Lw2Mx1KSX6Umlcc9PtCIesXW7O30gY"
    "YxAOhdCbSuH0Cy/Dts5ORMPhcbtFfrbmG2euxsfe/y7s6OwOugcnBEOGJYoNYyAmyQ4DwHNA6SpA"
    "YDgXwMsbhizeQoxtbsXRkPcAGVEzUgvAYAghsXTJfjCGx6SCtNaoqojj9/f+A5v+8wzi0egu6e+P"
    "hNYaFbEYnnr+JXz2G9+CYYaUclzK0k+eZvN5XPuNL+OYw5ejqyeYIzB+CDKqUETwGAKkHWPbZF4G"
    "ShcBAcPHABgMalvTlgbR8yQEGAXHrLeBVIZlqWqkKcUYg1gkjMV7LoLtOKAx+P9EBEdr3H3fPyBF"
    "kSBKQD+O1qirrkLrg2348hXXIB6Njns7kiCC7TgIWRZ++q2LsHiPRUhlMkHD1lhhABKu9V0kBSiE"
    "AAivxpR4FUDJIiBghCBgYmVCeq/3n+KpQIawBGRITuuIcFeADSrjccyvq3Xn0o3yucyMcCiEl197"
    "HRufeArRSCQ4/UfAXwn287v/jCtuuMkNCo4zHiCFQDqbxaL6BVh7+UWIRiLIO04QGBwLXgZAhj25"
    "G5wCdNf5Pdu2ps0eLgUIjJQFWOldlLm9ZCpQEWRUTkWJ/LAYYxCPRxEfYxebYYZlKby0+TV0dvdA"
    "KTnTlcyzAkdr1NVU4+obb8dtv/2Dlx4cZ+OQlOju7cURSw/BdRd9Bfl83ospB0pgNLBxY2/CKlEE"
    "JAAQngCGTwECIygAP3hgET3KxmCn7UA+RJAxhencmklwFUBFLOb2so8lt+z5sVu270DecYKbbgww"
    "MypiUXzlO9fi3n89iNrq6gmkB5U7rPXdK9F89hno6ukNioRGgxdMkTHlVuEWzQAAbLAewLApQGAE"
    "BdDS0uKNBnPajW2yJGioOcEMFbPcaOQ0H6WGS6xFGgGCO+Oei+88DSgBe8oTAM64+HI8+ezzqKwY"
    "/3IQpSS2d3bhzE8mceYnk0F6cAyoWPEMCjFJYxsQmQ0A0IrWYc3jkVQuA8CGGza8CsbzJGnnOIAX"
    "CFQxBbKmX5DEOAd+MBiRcNh7buAAjAVjDCLhMDq6urHqgkvR0dWNyATSg0IIdPX0ovnsM/Dhd68M"
    "0oMj4QUAVdwq5nYzSSLWpiMWt54CMGwAEBiFAkgmkxIEZvCj7r7xQQl3ryJJRqYvEMhwb5y+dLq/"
    "dXbUloDXqLJw/jyEvHXfAWNDa43KijiefPZ5fO7iy917UowzPei1V+fzefzg4q/iqBVL0e2Nbg8o"
    "AgMyJIvKG4MNSQEman/wBw/2jBQABEZRCuxvCgbTA0WtZS8QqOLWtJYECyGQSmXGnEYSRLBtB3t7"
    "m38dZ/QZhIABHEejtroa9/3rQZx/1Q9QWTH+TkZBhLzjIBIO4yeXXYhFuy0YV2n3nIe8AGBs+AAg"
    "gR8EgASGDwACo1AA/VVEZB4yjgGBiqpmq8Ia+ReYJJgZSgr0plLu4E85+kg+ESGXz2Ov3XfDikMO"
    "RCabDYJP48RxHMyvrcEtv74b3117G+pqqieUHkxlMli8xyL89FsXIWRZsIP04FCY3cO2eAkwuVu7"
    "8X+jvdyId35LS4sBABPJbTIObyM5yHH26pJVheXGAabJohZCIJ3N4YVXXoWlFHgMPqirQCQ++I63"
    "QRsOMgETwE0PVuGKG27Cz+/+M+bXTKx7sKunB8ccvhzXfuPLyOby051dLm8YgCBYVaFicsZEJJ2c"
    "toVUDwEjBwCB0e0GZDRBtP+4vY/AD5ESQ+IAbBgyKiGj0xcHIBCM0Xj8mecgxNjGdEkp0dOXwnHv"
    "fBuWH7QEqUwmsAImADMQj0bx5SuuQeuDbROa/qOUwo7Obnzsfe/ExWed7qYHg3iACwMyLKBiakgB"
    "EBgspACAJzeuffAFADRSABAY5XJQ35dgpvuJBmUCvDdGkmBVhKYtDsDMsJSFR594Crl8fsyDQLTW"
    "qIjHcO6pnxxzJ2HAzvjpQcOMz170LTz38iuoiI1/zLibHuzGF0/5OFad8GHsCNaO9fv/Km65U4AG"
    "fbRuAJDAxP8EwIlEoviwwEGMSmpa21sZAKTAfcbRICoSB2DAqg5Nxci8ohhjEImE0P70c3hp85Yx"
    "d/RJKdHd04cPvWslTvv4R7B1xw5Yu/pNNgH89OC2jk6sPv9S9KbSCFvWBNKDhO7ePlx+3hfw/sSb"
    "0dEVrB3bScYG4/n/wph7AYxYAOQzumOzxdU3Xc72jcYxr5AUnuff/+Jgw7AqLXc+wDQoAAZgKQtb"
    "d3Tg/rb1iEXGPm9OSHeH4KVnfw4nffC/sGX7DndzcJltPJot+F2WG558Gp9v+jaklGNL0RbgTbWF"
    "1ho/av46Dj34APT0pnbd9KA3hNeqKmplsyAhnZyTsS35TwBobR7Z/wdGqwC8eoAXb30xC8LfhTuG"
    "aOcXMO6AQqvSgrdNaOphhlISf1z3T+SdsY8DJ7idgI7j4PsXfQWn/7+PYEdXN7K5vKcIgrjAWHEc"
    "t2fgT63/xAVX/xBVFfEJrR3L2TYq4zGsveJi7DZ/3q6ZtSGANUPFFFRUFc//KwEiPPjkmrbXvPz/"
    "pCqA/noABv/BC80WmUQAhGoj0xa29cdZ/3v9Rmz6zzOIRaNjHgxCRNDGIG/b+O4FX8L137wAey6s"
    "x46ubqTS7kBV6U3HUVP04197rtzYfnpw7S9/i2tv/rm7cWgC6cG+dAb77b0nfnLZhRBCuN2fu1rM"
    "hoFQTbh4/T+D3T2d/EdgdPl/n1E7va3NrRoApKX/7uRFSpCIc2ExvaelrCoLwiKwxrQoAincwZO3"
    "/ub3uO6ir6IvnYYYo5VI5FoC3b19+PgH3ot3v/kNuPOPf+3fC9DV2zctewH60uk5c2Nrb47AZT9a"
    "i70XLcTH3vcubO/sHFcwT0mJru4evOXIw/Dd88/F5y+5AlUV8ensP5tZvPJfq7p4kJ2IpLE1GPgz"
    "MLr0X/9zx/RG3F0BZtmqxr/IkHyPzjt6p8Igryqw58ku5Hbk3EEh0/gl3fPTa3HgvosnZCb6m4Eq"
    "4zGkM1k89fyLc3ozEAAcd/o5+M9zL7gjvyZRqgSRt1xE4M7vfwdHrViKrt7xl/k6WmN+bQ2uXHMr"
    "vvnDn+4ya8fYMKwKC9XLaoud/kZYQmjbtD/W27bCj9dhlJI3JnWcQEK0otUQ86+I8B53ZtCgBxEQ"
    "qosgt33YnYSTir8b8Lpb7sDaKy528/oTuJbWGh1d3RBC4JD998WKQw6c1t2Ac8UVMMywpEIml8Np"
    "F34Tv7vhGuyxW/24y3zdtWPdOG/VyXj5tddxy6/vxvy62rm9dowAGEaoNgySAmybnQeAuPX/Annn"
    "d2iBTjQlVGtz66g/kDEpAD+yqMB/cHJORggRLeYGhKpDEBEBtqcnGKi1RnVlJe76Wys+/O77J7wg"
    "lIj6217TuRw4k8XQ4ofJw1crgmjOCL+PNgaxSASvbt2G1Rd8E7/+4ZVuma8e79oxN3Pzna9+Ea++"
    "vhX3/vtB1FaNf0JR2cPu+q9QbRgYXPyDAfOfJP0GGH4AaDHGercZNEGsv2n9qwy6nyzBQ7oDDSAi"
    "AqHq0PRlAwCAGZaSuPja6/Hq1m2IhEKTYs4KIkgZBAEnguMp6PWPP4EvNF+JUMhyld4E0oPGGPz4"
    "0gtwyP77oTeV6lfYcwo/rlZpQcWHRv/BMEIJMprbN+3xyHoA5Jfuj5Yx33FehJEE4U7yig+GwEB4"
    "fnRapwW7u+4jeGHzq/jqd65DOBwCxjkwJGDycRwHdTXVuOe+f6DpuhtQU1U5oRkCuXweNZUV+Onl"
    "F6GuphrZ3PTGTaYNBsLzI0VlyW//BfFv0AyTaBpd9V8hY/7EvGwAWwJ3OVndLaTY+UULsgH9NcvT"
    "hKM1aquqcM999+OK629yB4YGAz/LBsfRmFdbjR/f3oIf394yobVjUkr0ptM4ZP99cf2lFwDA3EsP"
    "+tZ0TbiYNc1EJLXtaAb/HBhb9N9nPCqTk8mkbFvTtp2A3wtLMDPv/C16fkt4fqSo3zKVOFqjtroK"
    "37v5v3Htzf+NBV6kOLADygNjGDVVlWi67nr89q/rMK+2ekLDRTu7u/HONx2Nq752DvrSmbmjALyD"
    "NFwbhogUr/0XlgRr/OvxG9c/4WfoxvoyE7KZmPAzNkxDhoUSwNogPD8CEZLTvj6c2d35d9H3rsd1"
    "t96B+nl1YGMmNcUVMD6Y3cRRKBTCFy+9Eg9tfBzVE+we3N7ZhZOPPxZfPf0U7OjqnhvlwgyQBML1"
    "0eLywwAJEBF+Boyt+KeQcT3JCzRQWGKdzuunhCUEGEOCgTIqEaqd5mAgBoJL1ZUVaLruBlz2w5+i"
    "qrICllJzN1o8izDMCCmFbC6Hz37jW3j19W3j6uXw8dODXz3tFHzig+/D9q5ZPly0340Owaqwhrb+"
    "AiykkDqrOzUyvwEGCvXGyngtAE40JWTbmjYbRDeTHDojwH0UEKmPzczqME8JVFVU4Ns/uQWrz78U"
    "qXQGtd5pE1gDM4s2BvFoFC9sfhWnXfhN5G0bllLj/l6ICKlMBt89/1wkjm5EZ3fvrM8MROqLB9KZ"
    "WQtLAOA7229s70gmk2MO/vmM2wXwAw4mLG5xck5KiNLBwFDN9FsBgKsEjDGYV1ON3/7PfTju9LPx"
    "t389iHk11YiELDc2ECiCGcPRGjVVVXhg/Sacc9l3EQmHvJqI8aUHtXarDm/45gU4YPFebkXoLIwJ"
    "sGaouEKoLgx2SuX+DQuhb5joa40/BtAMk0wmZfuPH9rCzL8VIUHFgoEgzwqYQdz9dtV4cfMWfPLc"
    "b+CsS6/Ey69txbyaaoRDIWhtoLUJlMEM4DgO5tVW49d/vheX/mANaqqqYPT404OZbBaL6utx2bmf"
    "h9Zm2g+dCeM12kfqo0VL6RmshSVhHL5/w9oNj6IJoqWlZdx+7aQkTgl8nXEMExULBjJCdWFYVVZR"
    "bTZdOFojGgkjGgnjtt/eg/9adRYuvPpHePHV11BTVYGaqgooJaG9HnRjXIUQ6ISpx08Pfv9nv8BP"
    "7vgV5k1k7Zhy15CvfEMj3nrU4ehNpWfXdGENyJhEeEGkpNVMBAL4WmDk1V8jMaEnt7S0aDRBPHbT"
    "+oeNbVqFJQWjSEpQApHdojO+g8MX6tpqt3Dkh7f9Eseu+iJOv/Ay3PW3VnT3plBdWYG6mmpUxuMI"
    "hyxIbziIW33Gc/KnHDCGUV1RgYu+dz3+1PpPd8LwOGsEGIyQFcLbjznSvcZscQO8wTqRBdGiY7/A"
    "MFJJ4eScp8IW3QOAWlvHF/zzmfAMrMQ6t0FICL4GVGQQEQHsMMLzIshUpOGkHdAMT9zRWkNKibqa"
    "auRtG7/+y734zV/uw96LFuLwpQejcekhOGTJvthr94Woq6lCJBRCNBKe0fc8lZRD7pyZIYSApSQ+"
    "3/Rt/PrH38XSA/ZDT9/YpwC526Md7L/3nu7E6DHOiJgxvMKfSH206OnPYCYpBGzzw7Y1bfZYG3+K"
    "MTnfvDuBBMteOeJhqeRh2tFmSJuwRchuyaD36Z5pHR8+EkSu7wgGcvk8Mrk8jDEIh0KeNVCFqgrX"
    "RZir7sDGJ59G2luwMtO/orsfIIu9Fy3E7264GvNqapDJ5cZkxmtjUFURx7oHHsaJ51yAeCxSNpZO"
    "SQhgmxHfpwKxvePFGukMSSKj+TUTzhzU/uP2lPf3E/rFJmUKZgIJ0drc6ojP0LUk6VbY2PnN+1bA"
    "giiyWzOwe+xpnxVQCma4wSIAlmW5PQQgsDHIZLN4cXMK2phxB6ZmA9FoxJ3dN9NvBK7wVsSieO7l"
    "V3D6hd/CL667AkrKsW+AFgJbtm2H7ThwQ1NlXv9hXN8/sjBW/PRnNlIpZbT9k/Yft/dNxukPTF5I"
    "jsBAwwkNlqiMbJKWPMDYhkEFMQbPCshty6HnP11lowCGw7/hiIrNP5s7lGO/hKUUtnV04uMfeC+u"
    "v/QC9PT1jbrZxw8qnnXplbjtt/egtrp63BuMpwUC2Dao2K8K0T1ixU5/JkFgzZ22LQ588raHOvy/"
    "n+hLT1Z4lBOXJGR7S3teCPoWSUFD4uf9sYCwWxcwgxmB0cJeN6Exxs0OzNGfcsR2HMyvq8Ev7vkL"
    "vv2Tm1FXPbqeAWMMotEInn3pFfz5H/9CRSw27q7D6YI1Q1VYiOwWLSoXzKxFSBKDv//kbQ/tGE/X"
    "XykmLT/S2tyq0QRhCdzhZO3HpSWH2l1eXUBszwq3e6DMLYCAmcWdMFyFa266HXfd24r6eXXI23bJ"
    "eg1XmRFikTC+85NbsL2jC5ZV5hugvWkwsT3jpaxiI6QQOue8bij0AzRBjLfstxiTmSDlZHuS2ta0"
    "2QRxAQmiIRVdnhVg1VgILyiu7QICdoKBaDiMsy+9En/95/9hYf0CCCHgaA096CcWiaCmqhIXXP1D"
    "tPzpr6iprOiP75QlnjyEakMIz4uUOv2NCElhDF/RfuMDHV7Tz6RptEkXv6amJtF8STMvP/WIf4qw"
    "eqO2Bw0OBQAimLxG18aOGSkRDphdCCGQz9tQSuK8VSfjpOPehwXzaj0nk/vLgNufeR7fXXsb7r63"
    "FdWVFWVv+gMAGKhZVgtVUWSfBsOQEmQc84LI28s37r8x4+37mzQFMOm7sNrb2wkEg1P562BuLRo+"
    "MwwZVYjtGUffcz2gYrvOAwI8jDEIWQraGFx87fW4/a4/4K1HHYGD91uMaCSCbR0dWP/4k7j/ofXo"
    "6Uu5J3+5C78X+IvuEYeqCg0Z9gm4eX+pSBhtLt54+8ZUIpFQrZh45H/Q25h8ksmkbGlp0UtPPfw3"
    "Vtg63sk5uug+QSJ0P9YBu7d80oIB5Qt5Q1Oz2RzS2Wz/37GX9ovHom45dzmb/T6GIcISNSvqQLJ4"
    "zb+0lNR556HH9nrkGAAYz8CPkZiSIumWhhYGQEz4qrFNjtx82tCNwgKI7xMEBANGBzNDa41QyEJd"
    "TTXqaqpRW12JuppqVFdWQBDNDuEnt/4kvndF8ZJfeIu3mCEUnYtmmGR7ckoO66npknA7BUX7jeuf"
    "MdpcJSNKDOkU7A8Iht3iB2cWdm4FzAi+InB/3OYtbczsOEO8ir/w/LDb8FNkdD4zaxmW0rH17RvX"
    "tP2vb1FPxduZsjaplpYWgyaIsEVXOFnnBaGkHDI1yBsdFt+zAjKugoBgwNzHW6Ib36fSHaEz9H5n"
    "IQTpvOmOKPoqGORZ1FPCVPZJ+mnBNBs+iyQRU5GErHErBCsWV3nPmsJ3FBAwk3jt8fF9KiCj0h2Y"
    "Owg/7QdtLmxb0/Za8oTkuIZ9jpYpbZRuaWnRyWRSPn7zI/fonPMrFVaylCsQqgshuigW1AYEzE18"
    "039BxK34K2b6g7UMKelknf/bdNMjP/ZM/ykNakz5pISWhhZGE4R09DnaNl1CCirqCjiM+F4VUJUq"
    "UAIBcw7WDBmVqNi3stiQT8Cd8w/WxpFCfK5g5c6U2sRTPyrFi2Bu+NmGzdDmS8ISotQAURKEyv2r"
    "i6ZFAgJmOxX7VZWM+ruBPyWNNpdtWPvQo4lEQk1V4K+QaTtnE4mEam1tdZad2vh7FZEfcLJFagPK"
    "eG5AQMC48Ap+YntXuIG/4gU/bs7fdtbP27Py6Pr2evZM/ym/+6dtWFrrylbjugLO53Re7yjpCtiM"
    "yMIoIguL+0kBAbOG/vhWGPG9Kkqlul3T35gcG/OZgh7/aTn6pm9a4k6uAD4nlBBMRVwB70Or2Lcy"
    "iAcEzF4IgGaIsEDl/tUlOxL7TX+bL3z85kc3TJfp7zOt41JbWlp0IpFQm25u+5WTc25UEUsx89Da"
    "Zi8eUHVANYRV3GcKCChrvNb3qgOqIcKl/X4VVkpnnf957Oa2qxNNCTXRIZ9jZdrnJbe2tupkMikr"
    "qkNn6ZzzmLSkGjJJ2MuXyrhC5ZKq8u7nDggYjJ/V2rcKVk3x5R5gGKGEMI7eoh1xCgDylu1M680+"
    "EwPTuaWhhR/43gMZMnQiG856U4KHThCyGaF5EVQsrgxKhQNmB/1dfjFEd48VDfoBYBAMERE7+uT2"
    "Wx/akkxObcFPKWZmY0IzTKIpoTbe9PBjxtFnSkvJIVYAsPOHuShe6sMMCCgPvPs1PH/4Q4uZtYoo"
    "pW19yaabH/1boml6/f5CZlSc/MmmSz9zxPVWzPqck7EdIio6o4AEoec/XchtzwbzAwLKD7+5rdJC"
    "9dLa/lFfg2FmR0WU0jn9h003tn3AkwFd/NFTz0yfp5RMJgUAPFn13DoZkm8pPTsAAAPd7Z2wu+2g"
    "RiCgfPCEX0YlapbVQVii1GIPLZWURptnhO0ctWHxhh4AU9LnP1pmemkatzS0cEtLi7YlTtCOeVUo"
    "KbnYKhfjZQYOqoGqCDoHA8oEL2AtwgJVB9dAhIoLPxhGkCDDnIaDj2y4dUMX2pM0k8IPzLwC6N8y"
    "/OSatte04eMBzpCgoTui/Q/aEqg6pAYyJAMlEDCzEADDIEmoPrgWKlayboUhYEiSQN45adMtbZsS"
    "iYTCDPn9hcy8AsBAfUD7jW0P6rz+pFBSQGCoX+SnB8MSVYfUlDS1AgKmHE/4QYSqgz2rtETRGgOO"
    "DCnl5PQ5m2559C4v3z+ps/3GS1koAABobW11Ek0J9fgt639jcva5MqSG1gcA/f6WiitUN9QGSiBg"
    "+ikU/kNqhl10w8yOFVGWk7W/9/gtj1w3WSu9JouyE5v+zMCpjd+1Iuo8J+vYRLCGPJABUgQn5aC7"
    "vRPGNkEXYcDU463wpkLhL9GzwgxbRZTl5OxfPHbjIyd6DXEzFvEvRtkpAACUSCRka2urs/zUxttU"
    "VH3SzoxCCTzRCZMPlEDAFOK5oCRds3944WdHRSylc859m/ZsezcATPZM/8mgbFyAAtgvF950U9un"
    "nJzzSxVRFjPsIY/03YGYQs2yOjcIE3QQBkwF3r0mQgI1S+sQqh5B+MNKmbzzD8rZH8Ql0zPcYzyU"
    "r6iw+94SlyRkx+bUX2VIrhzWHZAEYxv0PNkFuycfFAsFTB4Fef6qg2uGi/b3C7+2dbvmzFvbb2zv"
    "QBNmpMx3NJSjBeBCYFwCam1u1SHBx+q8XudaAkW6BwtShNVLaxGaFwnKhgMmB6+816q0BqzM0Qi/"
    "Ld7ZfmN7B5KQ5Sr8QDkrAMCtkGoCta1pSw8oAUuVdAe8bED1wTUDjRgBAeOloLa/eqmXcRqt8LsN"
    "PhItmPFc/3DMjjPSM6EaT2+M5Q39QYblSqdUYNCDFCH9SgqpF/pAglxVF7gEAaPBKztnhxHdI+Y2"
    "9jC7Pf3DCb+jH9d58S5f+GeqwWcszA4FAPQrgX1O2SdSFZp/qwypE4ZrHnLnCwrktmfR+0x3f/Q2"
    "UAIBw+JH+gmI71vlWpJOaUvSj/YbW6/L9nHyqTvats8W4QdmkwIAUBhMWba68b9VWJ3kZG3HWz9e"
    "rAATZAk4fTZ6n+6G02cHwcGA0vjBvrBE5QHeMI9hYkn9wp937rUEPti2pi2NJMre7C9kdikAwFUC"
    "ANAMs3zVEVfLsHWuzjkaDIFiu8i9DAFrRt9zPchuzYCUKNmuGbAL4t0LxjEI10VQuX8lRFgON4+S"
    "GaytiKV0Vt9R+0z8U62trU45R/tLMfsUgAslk0nR0tKil68+4itCqSuNo8GGDRENDWwyAOF2E2Ze"
    "SyP1Yp9bzRW4BAF+8BhAbM844ntVuP5/8eUdbpMagWVYCZ2zr9l04yPngUG4BDPe2TceyjsLUBpu"
    "aWkxiURCbVr7yFWcNyeSoKxQcugWYmCnoE5sURzVS73OrSBVuGvjRfllSKL6kFpU7ONu7WEu1dTD"
    "miSRUELorH3OphsfOa+pqUmAMKM9/RNh1t/+/b0DqxrfLCXdSVIs0jln+OCgIrDDSL3Uh8xr6X7r"
    "ILAGdhEIgHE3U4cXRFGxb6Xbxz/MCHpmdqQlFRvuM5pPfuymtt+VY23/WJn1CgAYUAKHnHr4PpYU"
    "dwhLvdHJ2o43WahoXAAEkHKzBKkXeuFkHIggNjD38U59EZKI71PhLuo08Lr7ij/FH+NlbP0fW9OJ"
    "T9z08Ppy6+obL3NCAQCAn3ppSDaEVG3sR0LJ1TrngLlEXADotwaMbZB6qQ/Z1zMAEMQG5iJeFx8M"
    "EJ4f8VZ0j+AGMgwIkBEldM75PdL5Uzb9fFPnXBF+YA4pAAA7pQmXn3bEmQRxDQkKa1sP6xJAACQF"
    "8h05pF7shd1nB9bAXKEgwq+iCvF9KhCeH3FdgOFPfS2UkO7GXr5k49qHm4GBg2Yaf4MpZW4pAJf+"
    "DEHDqsajlaCbhSUbnJytial4qhAYiA1oRubVNNKvpsAOgxT1//eAWYaX1ydBiCyMIrZnHCIkRwr+"
    "cv/GHsdsJqNXb7xx/Z/RBIFL3AzANP4GU85cVAAABuIC+yUbq+PV+IG05MnGNjDGFJ86DPTHBoQS"
    "cFI2Ui+nkNuR7VcOc+urn8P4qT0GQrUhxPaqgFUVAmtTspwX8KL8ICnDCibv/InyzmkbfrZh81wy"
    "+QczZxUAACCZlP7gxeWrj/g0CXG1kKLOcbMExQOEQH/xEAjId+aRfqUPdnceEBTEB8oZ38/XDFVh"
    "IbZnHOF5EQAYaWwcM7OWIalYc44ZF21a+/BVwNwz+QcztxWAS79LcMinDztAhdQPpBLv1XkDHs4a"
    "AAbcAgPktmeQeTUNp88GJAVpw3KiIK0nYwrRhTFEdov2V4D6ll0xCk99besHWevPP3bT+ocLK06n"
    "7feYAXYFBQAA8HK2DgAsO63xCwL0LaFElZN3RowN+ClDdgyyr2eQ2ZKGTjsDFoH/uIDpxTvx/UnR"
    "0YUxRBZGXT/fMcMKPvpPfaWMMTY0Xx56FN9qa2uz57LJP5hdRgEA2LmP4NQjD4Kkq6Si44w2MI4p"
    "nSkAdlIEJq+R25ZFdmsGTp/jZRECRTAt+B+zZsAwZEwhsiCKyG5Rt35/BD8f8CL8QkgRkjCOvt/R"
    "/OX2G9seBIDZWM8/EXYtBeCxkzWw+ohPCKIrhKX20jmn3yQs+eSCtCE7BrntWWRfz8DudWeU+LGD"
    "QBFMMn45t2fSqwqFSH0U4QUR98QfneAbAkGGpTCO6QDzJRvXtv0QAM+Fqr7xsEsqAAA7WQMNq46p"
    "U9L5BjPOkkoo1y0AoVQBEVBgEbh+pt2VR3ZrBvmuPNjxphOLwCqYEP7d6fn3JAWsKguR+ihCdWHX"
    "LRuF4INhmJilJSUYYOZbnQxf3H5b20sACE2zs5FnMth1FYBHYZR32amHHymkbCYp/gvM0LbWBCLQ"
    "ME1TviLwXAAn5SC3LYvcjix01g0e91sF/uMDhmfQaS8iAuHaMML1UVgVFiDc/P4IPj7AbtuuUFIJ"
    "SdCO+acgvmjDmra/Aztbgrsqu7wC8OjPFADAstVHHC9IXCAseaRxtBsfAIkRFQHQf/KbvHatgu1Z"
    "2D15r/iEAmVQjILPwy3XZZASsCothOdHEKoNQ4TFQPXeSILvBfiEFEpYEtp2ngKLKzatfegWwFP6"
    "d7aYuVbUMx4CBVBIgVuQSCRU10Gpkw3z16WlDjS2htFmZIsA2Gn+AADojEa+M4dcRw5On+1GqHd1"
    "ZVBE6CEJVtxCqC6MUG0YKqbc01578/gKn1cM/8SXQomQhM7pzRD4rlbpte0/bu8DQEgmRTks5SwX"
    "AgVQhEK3oOHMhgrpxFaD8UVpyX2NY2C0HjlGAAyxCmAYTsqB3ZNHvjMHu892TVkAJADQHFYIhb+X"
    "L/TsnvQqrhCqDcOqDkHFFUgKwPBoT3vXxwezkEJ6J/5WANdLR//o0Zsf3QbM/YKe8RIogGEovGmW"
    "fOLoqmjcnEqM04USh7BhGFsbJjB54jvsxfxYgRhQBjqrXWXQnYfTZ0PnNKDdpZNDFIJ/jdnA4Pdc"
    "IPAQBBmWUHEFqzoEqyoEGZVjF3q4RTwAIKWUpAS0rV8E+BaS9o833rBxK9Dv5+9y0f3REiiAkenf"
    "VQgAS963JBzbq+YTDHxWCDqaBEHnNZjZHU5aqqCoEF8ZEAHS/XdjG+iMA7vHhtNnw0k7MDnjjavy"
    "lYKnEAa/wkzd2sXehxtl90x216yXIQkZVVAVClaVe8oLS7gKrlDoi11zKMzMmoiUsCSIAO3ox4jE"
    "TyNhuuXBHzzYAwSCP1oCBTB6dgoUAsCK1Ue9F8KcyYbeL0PSMraGMUYDwKisAmCnG7/fOmB2FUJW"
    "Q6ccOGn3R2c12DYDpym5l++3FjCKVxxJHEb7fF/QGQPvRbiNVDIiIWMKKqag4hZkREKEPIFn7u/L"
    "H9XrDbyaYQZcM1/A2AYM3AfiG3Rn5q72lvY8EAj+WAkUwNgZoggOXX3UUiZzCoCPCyX3AgPa9q0C"
    "CPeoH4MyANwgoidUAADjWQk5DZPVcDIOTFZD5w1MXoMdtyR24DQt1CyF734M74EL/0A7KSmhCCIk"
    "IMISMiwhoxIyoiDDAmQJLy3qnfBcIPCjeQ8DL2sYbPpPewFo22wD4zcsaO1jax562H9oIPjjI1AA"
    "EyGZlGhoYb+I5OhPHF2VqdDHCkMnGeZ3yZCKsFtm7LsIfs/B6D/3QtPYdxsI/acpDGC0ATsM4xiY"
    "vAE7xj0hHQPjKwYv82Ac40bci0EEYVF/NyQpV5CFJSCUAFkEYUkIS4CUm8Vw3RLvvexkFRRedwyf"
    "aaHQKwGSAtp2NJj+AdAdUtu/8wN7YFDyhKRoaWkxCAR/XAQKYDJogkisS4jCopLDVx2+xEjxUcP0"
    "ETAfJUOKCpUBaCDUN+bXGyxcBFev0MC/71SPXCCQ/QJaAj91ubOa8itzilxn8LXG8dsw2IDBhUJv"
    "bA0AGwHczcR3blrTtsl/QjKZlC0Fijdg/AQKYHJx3YNBN+eyVYevIJIfAOFDYG6UISXZuKcyG2MY"
    "MOOyDgYz3Bk41qtO5rUGX5k9oScQkZBCCZCgAqHne0jgrg0/aXuo/50wKLEyIQMzf3IJFMBUUcQq"
    "AIDDV73hEE3OuwC8H8AxpGQtCQJr45ryzNpbPkHDtinPHvwAHntWj/RPeWaGsXUfQA+D+E8k6a8b"
    "b3j4URQIeCKRUK0rW01w2k8Ns/3mmh00QSSQEIN7zFd87o31ZPJHMeNdzPQmMC8TloyRIK/P3Y34"
    "M3ZSCjRhS2FqcE92YvbeKwgkSRC5sQIBr78iD+BJgP4N8N8A+cCmtQ++UnihRFNCtaLVoLmokxEw"
    "iZTbTTT38S2DIqfa0jOO3EvYfASAYwg4ipkaiLC7nzNnL2fOxgAGzOT6zgDQrxy8P3uXnKzvlwv/"
    "n4ldwfSTA0wSAkTCFXQ3juCmMpl5GxGeZNBDZPCgA93WfuP6Z4Z8JkiIQOinn0ABzCReFHtrw1Zq"
    "bR7q2x506psqI8Len4mXG8NHEOFgAEvAvAdJGRXSi8CD3eUWPJByY/ZygYNO5VHVAbiC7SsU1+Ig"
    "cgsTvai/WwTt1SxoBmuTA7CFCM8w6AkCP6qJNgoVeWbT9f/bOfhlEomEqq+v5yCYN7MECqCcaIJI"
    "tidpa8NW8k7DIYKRaEqojs2ZhQD2JDKLmbEfMy8mYB8wFjJQRwLVYFSQJPdU3qmkeJSFAF75LjPA"
    "2jADaSJ0g9EJ4DUGXhFEL4DwHBl+TrB5pTfeu+WZHzyTK3JJSlySkFgHBP58eREogPKG0ARKrEsI"
    "rARKKYVCjvnSMdG+Hq4i1jUQppaAGIPqAFHhVglhTyJSxux8GSEEDLMBm80klDGGs1KYrZopJyza"
    "rvK6V+d198bbN6aGfceeOQ8Are31jCBHX9YECmD24U6waU9SYutWwkpg2k9WL47R/9r19ewVRAX+"
    "+ywjUABzD3fMxSWukkgC2OorirGwDqivr+cWAGhoYW8rDhAIeEBAQEBAQEBAQEBAQEBAQEBAQEDA"
    "7OH/A/CUolGReDf0AAAAAElFTkSuQmCC"
)

# ─── Kleuren ──────────────────────────────────────────────────────────────

C_BG      = "#1a2e1e"   # donker groen tussenruimte
C_SURFACE = "#ede4c8"   # licht warm beige: panelen, header, footer
C_PANEL   = "#ddd4b0"   # iets donkerder beige: invoervelden
C_RAND    = "#8a7a50"   # warm bruin rand
C_CYAAN   = "#3a7a3a"   # donker groen accent (highlights, tabs)
C_GROEN   = "#2d7a35"   # OK groen (leesbaar op beige)
C_ROOD    = "#b83030"   # fout rood
C_AMBER   = "#9a6a00"   # amber waarschuwing
C_TEKST   = "#1e2a18"   # donker tekst op lichte achtergrond
C_DIM     = "#6a5e40"   # gedimde tekst op lichte achtergrond
C_SCHADUUW = "#4a3818"   # 3D schaduw: donker warm bruin
C_GLANS    = "#fdf9f0"   # 3D glans: licht crème
C_BTN     = "#2d6333"
C_BTN_HOV = "#3a7d40"

# ─── Firmware catalogus ───────────────────────────────────────────────────

RAW_BASE = "https://raw.githubusercontent.com"
API_BASE = "https://api.github.com"

CATALOG = {
    "BKOS-NUI": {
        "repo":   "brennyc86/BKOS-NUI",
        "branch": "main",
        "platforms": {
            "CYD 7 inch  ·  Sunton 8048S070": {
                "versie_bestand": "firmware/versie_esp32s3.txt",
                "ota_bin":        "firmware/bkos_esp32s3_8048s070.bin",
                "ser_bin":        "firmware/bkos_esp32s3_8048s070.bin",
                "chip":           "esp32s3",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 WROOM  ·  2.8\" 2432": {
                "versie_bestand": "firmware/versie_wroom.txt",
                "ota_bin":        "firmware/bkos_esp32wroom2432.bin",
                "ser_bin":        "firmware/bkos_esp32wroom2432.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  2.8\" (CYD28)": {
                "versie_bestand": "firmware/versie_cyd28.txt",
                "ota_bin":        "firmware/bkos_esp32cyd28.bin",
                "ser_bin":        "firmware/bkos_esp32cyd28.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  4\" Landscape (CYD40H)": {
                "versie_bestand": "firmware/versie_cyd40h.txt",
                "ota_bin":        "firmware/bkos_esp32cyd40h.bin",
                "ser_bin":        "firmware/bkos_esp32cyd40h.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  4\" Portrait (CYD40V)": {
                "versie_bestand": "firmware/versie_cyd40v.txt",
                "ota_bin":        "firmware/bkos_esp32cyd40v.bin",
                "ser_bin":        "firmware/bkos_esp32cyd40v.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "Raspberry Pi Pico W  ·  2.8\" 2432": {
                "versie_bestand": "firmware/versie_pico.txt",
                "ota_bin":        None,
                "ser_bin":        "firmware/bkos_pico1w2432.uf2",
                "chip":           "pico",
                "ser_addr":       None,
                "baud":           None,
                "ota_port":       None,
            },
        },
    },
    "BKOS-blanco  (firmware kiezer)": {
        "repo":   "brennyc86/BKOS-blanco",
        "branch": "main",
        "platforms": {
            "CYD 7 inch  ·  Sunton 8048S070": {
                "versie_bestand": "firmware/versie_esp32s3.txt",
                "ota_bin":        "firmware/bkos_blanco_esp32s3.bin",
                "ser_bin":        "firmware/bkos_blanco_esp32s3.bin",
                "chip":           "esp32s3",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 WROOM  ·  2.8\" 2432": {
                "versie_bestand": "firmware/versie_wroom.txt",
                "ota_bin":        "firmware/bkos_blanco_wroom.bin",
                "ser_bin":        "firmware/bkos_blanco_wroom.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  2.8\" (CYD28)": {
                "versie_bestand": "firmware/versie_cyd28.txt",
                "ota_bin":        "firmware/bkos_blanco_cyd28.bin",
                "ser_bin":        "firmware/bkos_blanco_cyd28.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  4\" Landscape (CYD40H)": {
                "versie_bestand": "firmware/versie_cyd40h.txt",
                "ota_bin":        "firmware/bkos_blanco_cyd40h.bin",
                "ser_bin":        "firmware/bkos_blanco_cyd40h.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "ESP32 CYD  ·  4\" Portrait (CYD40V)": {
                "versie_bestand": "firmware/versie_cyd40v.txt",
                "ota_bin":        "firmware/bkos_blanco_cyd40v.bin",
                "ser_bin":        "firmware/bkos_blanco_cyd40v.bin",
                "chip":           "esp32",
                "ser_addr":       "0x10000",
                "baud":           "921600",
                "ota_port":       3232,
            },
            "Raspberry Pi Pico W  ·  2.8\" 2432": {
                "versie_bestand": "firmware/versie_pico.txt",
                "ota_bin":        None,
                "ser_bin":        "firmware/bkos_blanco_pico.uf2",
                "chip":           "pico",
                "ser_addr":       None,
                "baud":           None,
                "ota_port":       None,
            },
        },
    },
}

# USB VID/PID → platform hint
USB_HINTS = {
    (0x2E8A, 0x000A): "Raspberry Pi Pico W  ·  2.8\" 2432",
    (0x2E8A, 0x0003): "Raspberry Pi Pico W  ·  2.8\" 2432",
    (0x2E8A, 0x0005): "Raspberry Pi Pico W  ·  2.8\" 2432",
    (0x303A, 0x1001): "CYD 7 inch  ·  Sunton 8048S070",
    (0x303A, 0x0002): "CYD 7 inch  ·  Sunton 8048S070",
    (0x1A86, 0x55D4): "CYD 7 inch  ·  Sunton 8048S070",
    (0x10C4, 0xEA60): None,   # CP2102 — niet uniek
    (0x1A86, 0x7523): None,   # CH340 — niet uniek
}

# URL van de releases.json index voor stabiele BKOS-NUI releases
BKOS_NUI_RELEASES_URL = f"{RAW_BASE}/brennyc86/BKOS-NUI/main/firmware/releases.json"

# Mapping van platform-naam naar veld in releases.json
RELEASES_SKEY = {
    "CYD 7 inch  ·  Sunton 8048S070":        "url_s3",
    "ESP32 WROOM  ·  2.8\" 2432":            "url_wroom",
    "ESP32 CYD  ·  2.8\" (CYD28)":           "url_cyd28",
    "ESP32 CYD  ·  4\" Landscape (CYD40H)":  "url_cyd40h",
    "ESP32 CYD  ·  4\" Portrait (CYD40V)":   "url_cyd40v",
    "Raspberry Pi Pico W  ·  2.8\" 2432":    "url_pico",
}


# ─── Hoofd applicatie ─────────────────────────────────────────────────────

class BkosInstaller(tk.Tk):

    def __init__(self):
        super().__init__()
        self.title("BKOS Installer")
        self.geometry("740x640")
        self.resizable(True, True)
        self.minsize(640, 560)
        self.configure(bg=C_BG)

        self._logo_img = None   # BKOS-logo voor header
        self._wifi_devices: dict[str, str] = {}   # hostname → ip
        self._download_cache: dict[str, str] = {} # url → lokaal pad
        self._stable_url_cache: dict[str, str] = {} # versie → download-url (stabiel kanaal)
        self._beta_sha_cache: dict[str, str]   = {} # versie → commit SHA (beta kanaal)
        self._flash_thread: threading.Thread | None = None
        self._zconf: "Zeroconf | None" = None
        self._actieve_tab = 0   # 0 = serieel, 1 = wifi

        try:
            import base64 as _b64, tkinter as _tk
            _img = _tk.PhotoImage(data=ICON_PNG_B64)
            self.wm_iconphoto(True, _img)
        except Exception:
            pass

        self._logo_img = self._laad_header_logo()
        self._bouw_ui()
        self._ververs_poorten()
        self.after(400, self._haal_versie_op)   # versie ophalen na opstart

        self.after(300, self._stel_min_hoogte_in)
        if MDNS_OK:
            threading.Thread(target=self._start_mdns, daemon=True).start()

    # ─── Scherm opbouwen ─────────────────────────────────────────────────

    def _bouw_ui(self):
        s = ttk.Style(self)
        s.theme_use("default")
        s.configure("TCombobox",
            fieldbackground=C_PANEL, background=C_PANEL,
            foreground=C_TEKST, selectbackground=C_RAND,
            arrowcolor=C_CYAAN, borderwidth=0, relief="flat")
        s.map("TCombobox", fieldbackground=[("readonly", C_PANEL)])
        s.configure("Horizontal.TProgressbar",
            troughcolor=C_PANEL, background=C_CYAAN,
            thickness=12, borderwidth=0)
        s.configure("TNotebook", background=C_PANEL, borderwidth=0)
        s.configure("TNotebook.Tab",
            background=C_PANEL, foreground=C_DIM,
            padding=[12, 6], font=("Segoe UI", 9))
        s.map("TNotebook.Tab",
            background=[("selected", C_SURFACE)],
            foreground=[("selected", C_CYAAN)])

        # ── Header ───────────────────────────────────────────────────────
        hdr = tk.Frame(self, bg=C_SURFACE, height=64)
        hdr.pack(fill="x", side="top")
        hdr.pack_propagate(False)
        if self._logo_img:
            tk.Label(hdr, image=self._logo_img, bg=C_SURFACE).pack(
                side="left", padx=(12, 8), pady=6)
        else:
            tk.Label(hdr, text="⚓", bg=C_SURFACE, fg=C_BTN,
                font=("Segoe UI", 18)).pack(side="left", padx=(16, 6), pady=8)
        hdr_tekst = tk.Frame(hdr, bg=C_SURFACE)
        hdr_tekst.pack(side="left", pady=8)
        tk.Label(hdr_tekst, text="BKOS Installer",
            bg=C_SURFACE, fg=C_TEKST,
            font=("Segoe UI", 12, "bold")).pack(anchor="w")
        tk.Label(hdr_tekst, text="Boordcomputer installatie hulpprogramma",
            bg=C_SURFACE, fg=C_DIM,
            font=("Segoe UI", 8)).pack(anchor="w")
        # Zeilboot rechts in header (eerst packen = meest rechts)
        tk.Label(hdr, text="⛵", bg=C_SURFACE, fg=C_BTN,
            font=("Segoe UI", 26)).pack(side="right", padx=(0, 20), pady=4)
        self._lbl_verbonden = tk.Label(hdr, text="", bg=C_SURFACE,
            fg=C_GROEN, font=("Segoe UI", 9))
        self._lbl_verbonden.pack(side="right", padx=4)
        # Accentstreep onder header
        tk.Frame(self, bg=C_BTN, height=3).pack(fill="x", side="top")

        # ── Hoofdgebied ───────────────────────────────────────────────────
        main = tk.Frame(self, bg=C_BG)
        main.pack(fill="both", expand=True, padx=0)

        # Linker kolom (instellingen)
        left = tk.Frame(main, bg=C_BG, width=360)
        left.pack(side="left", fill="y", padx=(12, 6), pady=12)
        left.pack_propagate(False)
        self._left_frame = left

        # Rechter kolom (log)
        right = tk.Frame(main, bg=C_BG)
        right.pack(side="left", fill="both", expand=True, padx=(0, 12), pady=12)

        self._bouw_links(left)
        self._bouw_rechts(right)

        # ── Footer ────────────────────────────────────────────────────────
        footer = tk.Frame(self, bg=C_SURFACE, height=56)
        footer.pack(fill="x", side="bottom")
        footer.pack_propagate(False)

        self._var_status = tk.StringVar(value="Gereed")
        tk.Label(footer, textvariable=self._var_status,
            bg=C_SURFACE, fg=C_DIM,
            font=("Segoe UI", 9)).pack(side="left", padx=16, pady=8)

        self._btn_install = tk.Button(footer, text="  ⬇  Installeer  ",
            bg=C_BTN, fg="white", font=("Segoe UI", 10, "bold"),
            relief="raised", bd=3, cursor="hand2", padx=8, pady=6,
            activebackground=C_BTN_HOV, activeforeground="white",
            command=self._start_installatie)
        self._btn_install.pack(side="right", padx=16, pady=8)

        self._progressbar = ttk.Progressbar(footer,
            style="Horizontal.TProgressbar",
            orient="horizontal", mode="determinate", maximum=100)
        self._progressbar.pack(side="right", padx=(0, 8), pady=14, ipadx=80)

    def _bouw_links(self, parent):
        def sectie(titel):
            # 4px groene linkerbalk via outer frame
            outer = tk.Frame(parent, bg=C_BTN)
            outer.pack(fill="x", pady=(10, 0))
            # Kaart: relief="raised" geeft ingebouwde 3D (highlight + schaduw)
            card = tk.Frame(outer, bg=C_SURFACE, bd=3, relief="raised")
            card.pack(fill="x", padx=(4, 0))
            # Titelregel: donkergroen + vet
            tk.Label(card, text=titel.upper(), bg=C_SURFACE,
                fg=C_BTN, font=("Segoe UI", 8, "bold"),
                anchor="w").pack(fill="x", padx=10, pady=(4, 3))
            # Groene scheidingslijn
            tk.Frame(card, bg=C_BTN, height=1).pack(fill="x")
            # Content-zone: relief="sunken" geeft ingedrukt effect
            f = tk.Frame(card, bg=C_PANEL, bd=2, relief="sunken")
            f.pack(fill="x", padx=6, pady=(5, 6))
            return f

        def rij(parent):
            r = tk.Frame(parent, bg=C_SURFACE)
            r.pack(fill="x", padx=8, pady=4)
            return r

        def lbl(parent, tekst):
            return tk.Label(parent, text=tekst, bg=C_SURFACE,
                fg=C_DIM, font=("Segoe UI", 9), width=10, anchor="w")

        def combo(parent, var, values, width=24, state="readonly"):
            cb = ttk.Combobox(parent, textvariable=var, values=values,
                state=state, width=width)
            return cb

        # ── Firmware ──────────────────────────────────────────────────────
        fw_frame = sectie("Firmware")

        r1 = rij(fw_frame)
        lbl(r1, "Type:").pack(side="left")
        self._var_fw = tk.StringVar(value=list(CATALOG.keys())[0])
        self._cb_fw = combo(r1, self._var_fw, list(CATALOG.keys()), width=22)
        self._cb_fw.pack(side="left")
        self._cb_fw.bind("<<ComboboxSelected>>", self._on_fw_change)

        r2 = rij(fw_frame)
        lbl(r2, "Platform:").pack(side="left")
        self._var_platform = tk.StringVar()
        self._cb_platform = combo(r2, self._var_platform, [], width=27)
        self._cb_platform.pack(side="left")
        self._cb_platform.bind("<<ComboboxSelected>>", self._on_platform_change)

        r_kanaal = rij(fw_frame)
        self._var_incl_beta = tk.BooleanVar(value=False)
        self._chk_beta = tk.Checkbutton(r_kanaal,
            text="incl. ontwikkeling",
            variable=self._var_incl_beta,
            bg=C_SURFACE, fg=C_TEKST,
            selectcolor=C_PANEL,
            activebackground=C_SURFACE,
            activeforeground=C_TEKST,
            font=("Segoe UI", 9),
            command=self._on_kanaal_change)
        self._chk_beta.pack(side="left")

        r3 = rij(fw_frame)
        lbl(r3, "Versie:").pack(side="left")
        self._var_versie = tk.StringVar(value="—")
        self._cb_versie = combo(r3, self._var_versie, [], width=18)
        self._cb_versie.pack(side="left", padx=(0, 6))
        tk.Button(r3, text="↻", bg=C_RAND, fg=C_TEKST,
            relief="flat", font=("Segoe UI", 9), cursor="hand2", padx=6,
            activebackground=C_RAND, activeforeground=C_CYAAN,
            command=self._haal_versie_op).pack(side="left")

        # ── Poort ─────────────────────────────────────────────────────────
        poort_frame = sectie("Poort / Apparaat")

        tabs = ttk.Notebook(poort_frame)
        tabs.pack(fill="x", padx=12, pady=8)
        tabs.bind("<<NotebookTabChanged>>",
            lambda e: setattr(self, "_actieve_tab", tabs.index(tabs.select())))

        # Tab Serieel
        t_ser = tk.Frame(tabs, bg=C_SURFACE)
        tabs.add(t_ser, text="Serieel (USB)")

        rs = tk.Frame(t_ser, bg=C_SURFACE)
        rs.pack(fill="x", pady=4)
        lbl(rs, "Poort:").pack(side="left")
        self._var_com = tk.StringVar()
        self._cb_com = combo(rs, self._var_com, [], width=20)
        self._cb_com.pack(side="left", padx=(0, 4))
        tk.Button(rs, text="↻", bg=C_RAND, fg=C_TEKST,
            relief="flat", padx=5, cursor="hand2",
            activebackground=C_RAND, activeforeground=C_CYAAN,
            command=self._ververs_poorten).pack(side="left")
        self._lbl_mcu = tk.Label(rs, text="", bg=C_SURFACE,
            fg=C_GROEN, font=("Segoe UI", 8))
        self._lbl_mcu.pack(side="left", padx=8)
        self._cb_com.bind("<<ComboboxSelected>>", self._on_com_select)

        # Tab WiFi
        t_wifi = tk.Frame(tabs, bg=C_SURFACE)
        tabs.add(t_wifi, text="WiFi (OTA)")

        rw = tk.Frame(t_wifi, bg=C_SURFACE)
        rw.pack(fill="x", pady=4)
        lbl(rw, "Apparaat:").pack(side="left")
        self._var_wifi = tk.StringVar()
        self._cb_wifi = combo(rw, self._var_wifi, [], width=20)
        self._cb_wifi.pack(side="left", padx=(0, 4))
        tk.Button(rw, text="↻", bg=C_RAND, fg=C_TEKST,
            relief="flat", padx=5, cursor="hand2",
            activebackground=C_RAND, activeforeground=C_CYAAN,
            command=self._scan_wifi).pack(side="left")

        rw2 = tk.Frame(t_wifi, bg=C_SURFACE)
        rw2.pack(fill="x", pady=(0, 2))
        lbl(rw2, "IP/hostnaam:").pack(side="left")
        self._var_wifi_ip = tk.StringVar()
        tk.Entry(rw2, textvariable=self._var_wifi_ip,
            bg=C_PANEL, fg=C_TEKST, insertbackground=C_TEKST,
            width=22, relief="flat", font=("Consolas", 9)).pack(side="left")
        tk.Label(rw2, text="(handmatig)", bg=C_SURFACE,
            fg=C_DIM, font=("Segoe UI", 8)).pack(side="left", padx=4)

        rw3 = tk.Frame(t_wifi, bg=C_SURFACE)
        rw3.pack(fill="x", pady=(0, 4))
        lbl(rw3, "Wachtwoord:").pack(side="left")
        self._var_ota_pw = tk.StringVar(value="bkos2025")
        tk.Entry(rw3, textvariable=self._var_ota_pw,
            bg=C_PANEL, fg=C_TEKST, insertbackground=C_TEKST,
            width=14, relief="flat", font=("Consolas", 9)).pack(side="left")
        tk.Label(rw3, text="(leeg = geen wachtwoord)", bg=C_SURFACE,
            fg=C_DIM, font=("Segoe UI", 8)).pack(side="left", padx=4)

        self._wifi_notitie = tk.Label(poort_frame,
            text="ℹ Schakel OTA-push in via het OTA-scherm op het apparaat.",
            bg=C_PANEL, fg=C_AMBER, font=("Segoe UI", 8),
            wraplength=300, justify="left")
        self._wifi_notitie.pack(anchor="w", padx=12, pady=(0, 6))

        # ── MCU override ──────────────────────────────────────────────────
        mcu_frame = sectie("MCU Type override")
        ro = rij(mcu_frame)
        lbl(ro, "MCU:").pack(side="left")
        alle_platforms = [p for fw in CATALOG.values()
                          for p in fw["platforms"]]
        self._var_mcu_override = tk.StringVar(value="(automatisch)")
        self._cb_mcu = combo(ro, self._var_mcu_override,
            ["(automatisch)"] + alle_platforms, width=27)
        self._cb_mcu.pack(side="left")
        self._cb_mcu.bind("<<ComboboxSelected>>", self._on_mcu_override)
        tk.Label(mcu_frame,
            text="Overschrijft automatische detectie.",
            bg=C_PANEL, fg=C_DIM, font=("Segoe UI", 8)).pack(
            anchor="w", padx=12, pady=(0, 6))

        # Init platforms
        self._on_fw_change()

    def _bouw_rechts(self, parent):
        # Zelfde 3D kaart-structuur als sectie()
        log_outer = tk.Frame(parent, bg=C_BTN)
        log_outer.pack(fill="both", expand=True, pady=(10, 0))
        log_card = tk.Frame(log_outer, bg=C_SURFACE, bd=3, relief="raised")
        log_card.pack(fill="both", expand=True, padx=(4, 0))

        tk.Label(log_card, text="LOG", bg=C_SURFACE, fg=C_BTN,
            font=("Segoe UI", 8, "bold"), anchor="w").pack(
            fill="x", padx=10, pady=(4, 3))
        tk.Frame(log_card, bg=C_BTN, height=1).pack(fill="x")

        log_content = tk.Frame(log_card, bg=C_PANEL, bd=2, relief="sunken")
        log_content.pack(fill="both", expand=True, padx=6, pady=(5, 6))

        self._log_widget = scrolledtext.ScrolledText(log_content,
            bg=C_SURFACE, fg=C_TEKST,
            font=("Consolas", 8), relief="flat",
            state="disabled", wrap="word",
            insertbackground=C_TEKST)
        self._log_widget.pack(fill="both", expand=True, padx=8, pady=8)

        # Log tags voor kleuren
        self._log_widget.tag_config("ok",  foreground=C_GROEN)
        self._log_widget.tag_config("err", foreground=C_ROOD)
        self._log_widget.tag_config("dim", foreground=C_DIM)
        self._log_widget.tag_config("hl",  foreground=C_CYAAN)

        tk.Button(parent, text="Log wissen",
            bg=C_PANEL, fg=C_DIM, relief="raised", bd=2,
            font=("Segoe UI", 8), cursor="hand2",
            activebackground=C_PANEL, activeforeground=C_TEKST,
            command=self._log_wissen).pack(anchor="e", pady=(4, 0))

    # ─── Event handlers ───────────────────────────────────────────────────

    def _on_fw_change(self, event=None):
        fw = self._var_fw.get()
        cfg = CATALOG.get(fw, {})
        platforms = list(cfg.get("platforms", {}).keys())
        self._cb_platform["values"] = platforms
        if platforms:
            self._var_platform.set(platforms[0])
        else:
            self._var_platform.set("(geen platforms beschikbaar)")
        self._var_versie.set("—")
        self._cb_versie["values"] = []
        self._stable_url_cache = {}
        self._beta_sha_cache   = {}
        # Ontwikkeling-vinkje alleen relevant voor BKOS-NUI
        if hasattr(self, "_chk_beta"):
            if fw == "BKOS-NUI":
                self._chk_beta.config(state="normal")
            else:
                self._var_incl_beta.set(False)
                self._chk_beta.config(state="disabled")
        if hasattr(self, "_log_widget"):
            self._haal_versie_op()

    def _on_platform_change(self, event=None):
        self._var_versie.set("—")
        self._cb_versie["values"] = []
        self._stable_url_cache = {}
        self._beta_sha_cache   = {}
        if hasattr(self, "_log_widget"):
            self._haal_versie_op()

    def _on_kanaal_change(self, event=None):
        self._var_versie.set("—")
        self._cb_versie["values"] = []
        self._stable_url_cache = {}
        self._beta_sha_cache   = {}
        if hasattr(self, "_log_widget"):
            self._haal_versie_op()

    def _on_mcu_override(self, event=None):
        val = self._var_mcu_override.get()
        if val != "(automatisch)":
            self._var_platform.set(val)

    def _on_com_select(self, event=None):
        label = self._var_com.get()
        self._detecteer_mcu_uit_label(label)

    def _detecteer_mcu_uit_label(self, label):
        if not SERIAL_OK:
            return
        for p in list_ports.comports():
            if p.device in label:
                hint = USB_HINTS.get((p.vid, p.pid))
                if hint:
                    self._lbl_mcu.config(text=f"✓ {hint.split('·')[0].strip()}")
                    if self._var_mcu_override.get() == "(automatisch)":
                        self._var_platform.set(hint)
                    return
                else:
                    self._lbl_mcu.config(text="")
                return
        self._lbl_mcu.config(text="")

    # ─── COM poorten ──────────────────────────────────────────────────────

    def _ververs_poorten(self):
        if not SERIAL_OK:
            self._cb_com["values"] = ["pyserial niet gevonden — pip install pyserial"]
            return
        poorten = []
        for p in sorted(list_ports.comports(), key=lambda x: x.device):
            hint = USB_HINTS.get((p.vid, p.pid))
            if hint:
                label = f"{p.device}  —  {hint.split('·')[0].strip()}"
            else:
                desc = (p.description or "onbekend")[:40]
                label = f"{p.device}  —  {desc}"
            poorten.append(label)
        self._cb_com["values"] = poorten
        if poorten:
            if not self._var_com.get() or self._var_com.get() not in poorten:
                self._var_com.set(poorten[0])
            self._detecteer_mcu_uit_label(poorten[0])
        else:
            self._var_com.set("(geen poorten gevonden)")
            self._lbl_mcu.config(text="")

    # ─── WiFi / mDNS ──────────────────────────────────────────────────────

    def _start_mdns(self):
        try:
            self._wifi_devices = {}
            self._zconf = Zeroconf()
            listener = _MdnsListener(self)
            ServiceBrowser(self._zconf, "_arduino._tcp.local.", listener)
        except Exception as e:
            self._log(f"mDNS fout: {e}", "err")

    def _scan_wifi(self):
        if not MDNS_OK:
            self._log("zeroconf niet gevonden — pip install zeroconf", "err")
            return
        self._log("Scannen op Arduino OTA-apparaten (3s)...", "dim")
        self._wifi_devices = {}
        if self._zconf:
            try:
                self._zconf.close()
            except Exception:
                pass
        threading.Thread(target=self._start_mdns, daemon=True).start()
        self.after(3000, self._ververs_wifi_lijst)

    def _ververs_wifi_lijst(self):
        items = [f"{h}  [{ip}]" for h, ip in self._wifi_devices.items()]
        self._cb_wifi["values"] = items
        if items:
            self._var_wifi.set(items[0])
            self._log(f"Gevonden: {len(items)} apparaat/apparaten", "ok")
        elif not self._var_wifi.get():
            self._var_wifi.set("")

    def _wifi_ip_uit_selectie(self):
        """Haal het IP-adres op uit de WiFi-selectie of het handmatige veld."""
        manual = self._var_wifi_ip.get().strip()
        if manual:
            return manual
        sel = self._var_wifi.get()
        if "[" in sel:
            m = re.search(r'\[(.+?)\]', sel)
            if m:
                return m.group(1)
        return sel.strip()

    # ─── Versie ophalen ───────────────────────────────────────────────────

    def _haal_versie_op(self):
        threading.Thread(target=self._versie_thread, daemon=True).start()

    def _versie_thread(self):
        fw        = self._var_fw.get()
        plat_k    = self._var_platform.get()
        incl_beta = self._var_incl_beta.get() if hasattr(self, "_var_incl_beta") else False
        cfg       = CATALOG.get(fw, {})
        plat      = cfg.get("platforms", {}).get(plat_k)
        if not plat:
            self._log(f"Geen platform voor: {plat_k}", "err")
            return

        # ── BKOS-NUI: stabiel + optioneel ontwikkeling ───────────────────
        if fw == "BKOS-NUI":
            skey         = RELEASES_SKEY.get(plat_k)
            alle_versies = []
            url_map      = {}
            sha_map      = {}

            # Stabiele releases ophalen uit releases.json
            if skey:
                self._log("Stabiele releases ophalen...", "dim")
                try:
                    with urllib.request.urlopen(BKOS_NUI_RELEASES_URL, timeout=10) as r:
                        data = json.loads(r.read().decode())
                    for entry in data.get("releases", []):
                        url_v = entry.get(skey, "")
                        if url_v:
                            v = entry["versie"]
                            alle_versies.append(v)
                            url_map[v] = url_v
                    self._log(f"{len(alle_versies)} stabiele versie(s) gevonden", "ok")
                except Exception as e:
                    self._log(f"Stabiele releases ophalen mislukt: {e}", "err")
            else:
                self._log(f"Geen releases.json sleutel voor: {plat_k}", "err")

            # Ontwikkelversies ophalen via commit history (alleen als vinkje aan)
            if incl_beta:
                bin_rel        = plat.get("ser_bin") or plat.get("ota_bin")
                versie_bestand = plat.get("versie_bestand", "")
                repo           = cfg["repo"]
                if bin_rel:
                    api_url = (f"{API_BASE}/repos/{repo}/commits"
                               f"?path={bin_rel}&per_page=20")
                    self._log("Ontwikkelversies ophalen via GitHub...", "dim")
                    try:
                        req = urllib.request.Request(
                            api_url,
                            headers={"Accept": "application/vnd.github.v3+json"})
                        with urllib.request.urlopen(req, timeout=15) as r:
                            if r.status == 403:
                                self._log("GitHub rate limit bereikt — probeer later.", "err")
                            else:
                                commits = json.loads(r.read().decode())
                                beta_cnt = 0
                                for commit in commits:
                                    sha = commit["sha"]
                                    msg = commit["commit"]["message"].split("\n")[0]
                                    m = re.search(r'\b(\d+\.\d+\.\d{6}\.\d+)\b', msg)
                                    if m:
                                        v = m.group(1)
                                    else:
                                        try:
                                            vurl = (f"{API_BASE}/repos/{repo}/contents/"
                                                    f"{versie_bestand}?ref={sha}")
                                            vreq = urllib.request.Request(
                                                vurl,
                                                headers={"Accept": "application/vnd.github.v3+json"})
                                            with urllib.request.urlopen(vreq, timeout=10) as vr:
                                                vdata = json.loads(vr.read().decode())
                                            v = base64.b64decode(vdata["content"]).decode().strip()
                                        except Exception:
                                            continue
                                    if v and v not in sha_map and v not in url_map:
                                        alle_versies.append(v)
                                        sha_map[v] = sha
                                        beta_cnt += 1
                                self._log(f"{beta_cnt} ontwikkelversie(s) gevonden", "ok")
                    except Exception as e:
                        self._log(f"Ontwikkelversies ophalen mislukt: {e}", "err")

            self._stable_url_cache = url_map
            self._beta_sha_cache   = sha_map

            # Bij incl. ontwikkeling: sorteer op versienummer nieuwste eerst
            if incl_beta and alle_versies:
                def _sleutel(v):
                    try:
                        d = v.split(".")
                        return (int(d[2]), int(d[3]), int(d[0]), int(d[1]))
                    except Exception:
                        return (0, 0, 0, 0)
                alle_versies.sort(key=_sleutel, reverse=True)

            if alle_versies:
                self.after(0, lambda vs=alle_versies: [
                    self._var_versie.set(vs[0]),
                    self._cb_versie.config(values=vs)
                ])
            else:
                self._log("Geen versies beschikbaar.", "err")
            return

        # ── Laatste build: versie.txt (voor BKOS-blanco) ─────────────────
        url = (f"{RAW_BASE}/{cfg['repo']}/{cfg['branch']}/"
               f"{plat['versie_bestand']}")
        self._log("Versie ophalen...", "dim")
        try:
            with urllib.request.urlopen(url, timeout=10) as r:
                versie = r.read().decode().strip()
            self.after(0, lambda v=versie: [
                self._var_versie.set(v),
                self._cb_versie.config(values=[v])
            ])
            self._log(f"Laatste versie: {versie}", "ok")
        except Exception as e:
            self._log(f"Versie ophalen mislukt: {e}", "err")

    # ─── Installatie starten ──────────────────────────────────────────────

    def _start_installatie(self):
        if self._flash_thread and self._flash_thread.is_alive():
            self._log("⚠ Al bezig...", "err")
            return

        # Poort bepalen
        if self._actieve_tab == 1:
            methode = "wifi"
            host = self._wifi_ip_uit_selectie()
            if not host:
                messagebox.showwarning("WiFi", "Geen WiFi-apparaat geselecteerd of IP ingevoerd.")
                return
            if not messagebox.askyesno("OTA bevestigen",
                    "Controleer: is OTA-push ingeschakeld op het apparaat?\n"
                    "(OTA-scherm → schakelaar aan)\n\n"
                    "Doorgaan?"):
                return
        else:
            methode = "serieel"
            com_label = self._var_com.get()
            host = com_label.split()[0] if com_label else ""
            if not host or "geen" in host.lower():
                messagebox.showwarning("Poort", "Geen seriële poort geselecteerd.")
                return

        # Platform en config
        fw     = self._var_fw.get()
        plat_k = self._var_platform.get()
        cfg    = CATALOG.get(fw, {})
        plat   = cfg.get("platforms", {}).get(plat_k)
        if not plat:
            messagebox.showerror("Fout", f"Geen configuratie voor '{plat_k}'.")
            return

        if plat["chip"] == "pico" and methode == "wifi":
            messagebox.showinfo("Pico W",
                "Pico W ondersteunt geen WiFi-flash.\n"
                "Gebruik de seriële modus (BOOTSEL-modus).")
            return

        self._btn_install.config(state="disabled")
        self._progressbar["value"] = 0
        self._flash_thread = threading.Thread(
            target=self._flash_thread_func,
            args=(methode, host, fw, plat_k, plat, cfg),
            daemon=True
        )
        self._flash_thread.start()

    # ─── Flash thread ─────────────────────────────────────────────────────

    def _flash_thread_func(self, methode, host, fw, plat_k, plat, cfg):
        try:
            repo    = cfg["repo"]
            branch  = cfg["branch"]
            bin_key = "ota_bin" if methode == "wifi" else "ser_bin"
            bin_rel = plat.get(bin_key)
            if not bin_rel:
                self._log(f"Geen firmware geconfigureerd voor methode '{methode}'.", "err")
                return

            versie = self._var_versie.get()

            if versie in self._stable_url_cache:
                # Stabiele release via releases.json URL
                url    = self._stable_url_cache[versie]
                # Versie in de bestandsnaam → elk versienummer krijgt een eigen
                # temp-bestand, zodat nooit een oude download wordt hergebruikt.
                naam   = f"{versie}_{url.split('/')[-1]}"
                lokaal = self._download(url, naam)

            elif versie in self._beta_sha_cache:
                # Ontwikkelversie via commit SHA (SHA maakt de naam al uniek)
                sha = self._beta_sha_cache[versie]
                url = f"{RAW_BASE}/{repo}/{sha}/{bin_rel}"
                naam   = f"{sha[:8]}_{os.path.basename(bin_rel)}"
                lokaal = self._download(url, naam)

            else:
                # Laatste build fallback (BKOS-blanco of cache verlopen):
                # nooit cachen, want de main-branch bin verandert zonder dat
                # de URL wijzigt.
                url    = f"{RAW_BASE}/{repo}/{branch}/{bin_rel}"
                lokaal = self._download(url, os.path.basename(bin_rel),
                                        forceer_vers=True)

            if not lokaal:
                return

            chip = plat.get("chip", "")
            if chip == "pico":
                self._flash_pico(lokaal)
            elif methode == "wifi":
                self._flash_ota(host, lokaal, plat.get("ota_port", 3232))
            else:
                self._flash_esptool(host, lokaal, plat)
        finally:
            self.after(0, lambda: self._btn_install.config(state="normal"))
            self.after(0, lambda: self._set_status("Gereed"))

    # ─── Download ─────────────────────────────────────────────────────────

    def _download(self, url, naam, forceer_vers=False):
        # Cache alleen gebruiken als de URL stabiel naar dezelfde inhoud wijst
        # (tag-URL of commit-SHA). Bij forceer_vers (main-branch) altijd opnieuw.
        if not forceer_vers and url in self._download_cache:
            pad = self._download_cache[url]
            if os.path.exists(pad):
                self._log(f"Cache: {naam}", "dim")
                return pad

        tmp = os.path.join(tempfile.gettempdir(), f"bkos_{naam}")
        self._log(f"Downloaden: {naam}")
        self._set_status(f"Downloaden {naam}...")
        self._set_progress(0)
        try:
            with urllib.request.urlopen(url, timeout=60) as resp:
                totaal = int(resp.headers.get("Content-Length", 0) or 0)
                gedaan = 0
                with open(tmp, "wb") as f:
                    while True:
                        chunk = resp.read(8192)
                        if not chunk:
                            break
                        f.write(chunk)
                        gedaan += len(chunk)
                        if totaal:
                            self._set_progress(int(gedaan * 45 / totaal))
            kb = os.path.getsize(tmp) // 1024
            self._log(f"✓ {naam}  ({kb} KB)", "ok")
            self._download_cache[url] = tmp
            return tmp
        except Exception as e:
            self._log(f"Download mislukt: {e}", "err")
            return None

    # ─── Serieel flashing (esptool) ───────────────────────────────────────

    def _flash_esptool(self, port, firmware_pad, plat):
        chip = plat.get("chip", "esp32")
        baud = plat.get("baud", "921600")
        addr = plat.get("ser_addr", "0x10000")

        self._log(f"Serieel flashing: {port}  chip={chip}  adres={addr}")
        self._set_status(f"Flashing {port}...")
        self._set_progress(45)

        # Maak tijdelijk OTA-data reset bestand (8KB van 0xFF).
        # Na OTA-update start ESP32 van ota_0/ota_1 partitie, niet factory.
        # Door otadata (0xE000, 8KB) te wissen boot de bootloader opnieuw van
        # factory (0x10000) waar de nieuwe firmware naartoe geschreven wordt.
        otadata_fd, otadata_pad = tempfile.mkstemp(suffix="_otadata_reset.bin")
        try:
            with os.fdopen(otadata_fd, "wb") as f:
                f.write(b"\xff" * 8192)

            esptool_args = [
                "--chip",  chip,
                "--port",  port,
                "--baud",  baud,
                "--before", "default_reset",
                "--after",  "hard_reset",
                "write_flash", "-z",
                "0xe000", otadata_pad,  # OTA boot-selectie wissen → factory
                addr,       firmware_pad
            ]

            if getattr(sys, "frozen", False):
                # PyInstaller .exe: gebruik module-API (stub-bestanden via --collect-data)
                try:
                    import esptool
                    def _voortgang(pct):
                        self._set_progress(45 + int(pct * 0.55))
                    old_stdout = sys.stdout
                    sys.stdout = _EsptoolCapture(self, _voortgang)
                    try:
                        esptool.main(esptool_args)
                    finally:
                        sys.stdout = old_stdout
                    self._log("✅ Flash geslaagd!", "ok")
                    self._set_progress(100)
                except SystemExit as e:
                    if str(e) != "0":
                        self._log(f"esptool fout: {e}", "err")
                except Exception as e:
                    self._log(f"esptool fout: {e}", "err")
            else:
                # Dev-modus: subprocess via python -m esptool
                # (vindt stub-bestanden altijd correct via module-pad)
                cmd = [sys.executable, "-m", "esptool"] + esptool_args
                ok = self._run_subprocess(cmd, 45, 55)
                if not ok:
                    self._log("→ Als de poort bezet is: sluit Arduino IDE / wacht 5s en probeer opnieuw.", "dim")
        finally:
            try:
                os.unlink(otadata_pad)
            except OSError:
                pass

    # ─── WiFi OTA flashing ────────────────────────────────────────────────

    def _flash_ota(self, host, firmware_pad, ota_port=3232):  # noqa: C901
        self._log(f"WiFi OTA → {host}:{ota_port}")
        self._set_status(f"OTA naar {host}...")
        self._set_progress(45)

        # Firmware inladen en MD5 berekenen
        try:
            with open(firmware_pad, "rb") as f:
                fw_data = f.read()
        except OSError as e:
            self._log(f"Kan firmware niet lezen: {e}", "err")
            return
        fw_size = len(fw_data)
        fw_md5  = hashlib.md5(fw_data).hexdigest()
        fw_naam = os.path.basename(firmware_pad)
        self._log(f"Firmware: {fw_size // 1024} KB  MD5: {fw_md5[:16]}...", "dim")

        # TCP server aanmaken (device verbindt terug naar ons)
        local_port = random.randint(10000, 60000)
        tcp_srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        tcp_srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            tcp_srv.bind(("", local_port))
            tcp_srv.listen(1)
        except OSError as e:
            self._log(f"TCP server aanmaken mislukt (poort {local_port}): {e}", "err")
            tcp_srv.close()
            return

        invite = f"0 {local_port} {fw_size} {fw_md5}\n"

        def _stuur_invite_en_wacht():
            """Stuurt UDP invite, retourneert antwoord-string of None bij timeout."""
            for poging in range(3):
                s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                s.settimeout(5)
                try:
                    s.sendto(invite.encode(), (host, ota_port))
                    return s.recv(69).decode().strip()
                except socket.timeout:
                    if poging == 0:
                        self._log("Wachten op reactie...", "dim")
                except Exception as e:
                    self._log(f"UDP fout: {e}", "err")
                    return None
                finally:
                    s.close()
            return None

        def _authenticeer(nonce, pw, gebruik_md5_pw, oud_protocol):
            """Challenge-response authenticatie. Retourneert True bij succes."""
            cnonce_src = f"{fw_naam}{fw_size}{fw_md5}{host}"
            if oud_protocol:
                # ESP32 core 2.x: MD5 protocol (nonce = 32 chars)
                cnonce  = hashlib.md5(cnonce_src.encode()).hexdigest()
                pw_hash = hashlib.md5(pw.encode()).hexdigest()
                resp    = hashlib.md5(f"{pw_hash}:{nonce}:{cnonce}".encode()).hexdigest()
            else:
                # ESP32 core 3.x: PBKDF2-SHA256 protocol (nonce = 64 chars)
                cnonce  = hashlib.sha256(cnonce_src.encode()).hexdigest()
                pw_hash = (hashlib.md5(pw.encode()).hexdigest() if gebruik_md5_pw
                           else hashlib.sha256(pw.encode()).hexdigest())
                salt    = f"{nonce}:{cnonce}"
                derived = hashlib.pbkdf2_hmac("sha256", pw_hash.encode(), salt.encode(), 10000)
                resp    = hashlib.sha256(f"{derived.hex()}:{nonce}:{cnonce}".encode()).hexdigest()
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.settimeout(10)
            try:
                s.sendto(f"200 {cnonce} {resp}\n".encode(), (host, ota_port))
                ack = s.recv(32).decode().strip()
                return ack == "OK"
            except Exception:
                return False
            finally:
                s.close()

        # ── Fase 1: invite sturen ────────────────────────────────────────────
        self._log("Uitnodiging sturen naar device...", "dim")
        data = _stuur_invite_en_wacht()
        if data is None:
            self._log("✗ Geen reactie van device.", "err")
            self._log("→ OTA-push ingeschakeld? (OTA-scherm op apparaat → schakelaar aan)", "dim")
            self._log("→ WiFi verbonden op het apparaat?", "dim")
            tcp_srv.close()
            return
        self._log(f"Device reactie: {data}", "dim")

        # ── Fase 2: authenticatie ────────────────────────────────────────────
        if data != "OK":
            if not data.startswith("AUTH "):
                self._log(f"✗ Onverwacht antwoord: {data}", "err")
                tcp_srv.close()
                return
            nonce = data.split(" ", 1)[1]
            pw    = self._var_ota_pw.get().strip()
            if not pw:
                self._log("✗ Device vraagt wachtwoord — vul OTA-wachtwoord in.", "err")
                tcp_srv.close()
                return

            if len(nonce) == 32:
                self._log("Authenticeren (MD5 protocol, core 2.x)...", "dim")
                ok_auth = _authenticeer(nonce, pw, gebruik_md5_pw=True, oud_protocol=True)
            else:
                self._log("Authenticeren (PBKDF2-SHA256, core 3.x)...", "dim")
                ok_auth = _authenticeer(nonce, pw, gebruik_md5_pw=False, oud_protocol=False)
                if not ok_auth:
                    # Fallback: opnieuw inviten en MD5 wachtwoord-hash proberen
                    self._log("SHA256 mislukt, opnieuw proberen met MD5 wachtwoord...", "dim")
                    data2 = _stuur_invite_en_wacht()
                    if data2 and data2.startswith("AUTH "):
                        nonce2  = data2.split(" ", 1)[1]
                        ok_auth = _authenticeer(nonce2, pw, gebruik_md5_pw=True, oud_protocol=False)

            if not ok_auth:
                self._log("✗ Authenticatie mislukt.", "err")
                self._log("→ Controleer OTA-wachtwoord (standaard: bkos2025).", "dim")
                tcp_srv.close()
                return
            self._log("✓ Authenticatie geslaagd.", "ok")

        # ── Fase 3: wachten op TCP-verbinding van device ─────────────────────
        self._log("Wachten op verbinding van device (max 15 s)...", "dim")
        self.after(0, lambda: self._progressbar.config(mode="indeterminate"))
        self.after(0, lambda: self._progressbar.start(10))

        tcp_srv.settimeout(15)
        conn = None
        try:
            conn, addr = tcp_srv.accept()
            self._log(f"✓ Device verbonden vanaf {addr[0]}", "ok")
        except socket.timeout:
            self._log("✗ Device kon geen TCP-verbinding maken (timeout 15 s).", "err")
            self._log("→ Windows Firewall blokkeert mogelijk inkomende verbindingen.", "dim")
            self._log("  Voeg een uitzondering toe voor python.exe of BKOS_Installer.exe.", "dim")
            return
        except Exception as e:
            self._log(f"✗ TCP accept fout: {e}", "err")
            return
        finally:
            self.after(0, lambda: self._progressbar.stop())
            self.after(0, lambda: self._progressbar.config(mode="determinate"))
            tcp_srv.close()

        # ── Fase 4: firmware uploaden in blokken van 1024 bytes ──────────────
        self._set_progress(50)
        BLOK      = 1024
        verzonden = 0
        laaste_ok = False
        conn.settimeout(10)
        try:
            while verzonden < fw_size:
                blok = fw_data[verzonden:verzonden + BLOK]
                conn.sendall(blok)
                verzonden += len(blok)
                try:
                    res = conn.recv(10).decode().strip()
                    laaste_ok = "OK" in res
                except socket.timeout:
                    self._log(f"✗ Timeout bij byte {verzonden}.", "err")
                    return
                pct = 50 + int(verzonden * 50 / fw_size)
                self._set_progress(pct)
                if verzonden % (BLOK * 32) < BLOK or verzonden >= fw_size:
                    self._log(
                        f"Upload: {verzonden * 100 // fw_size}%"
                        f"  ({verzonden // 1024}/{fw_size // 1024} KB)", "hl")

            # Eindbevestiging ophalen als laatste chunk nog geen OK gaf
            if not laaste_ok:
                conn.settimeout(30)
                for _ in range(10):
                    try:
                        res = conn.recv(32).decode().strip()
                        if "OK" in res:
                            laaste_ok = True
                            break
                    except socket.timeout:
                        continue

            if laaste_ok:
                self._log("✅ OTA upload geslaagd! Device herstart...", "ok")
            else:
                self._log("⚠ Upload voltooid — geen eindbevestiging (device herstart al).", "dim")
            self._set_progress(100)

        except Exception as e:
            self._log(f"✗ Upload fout: {e}", "err")
        finally:
            conn.close()

    # ─── Pico W UF2 flashing ─────────────────────────────────────────────

    def _flash_pico(self, firmware_pad):
        self._log("Pico W — zoek BOOTSEL-schijf (RPI-RP2)...")
        self._set_status("Zoeken naar Pico W BOOTSEL-schijf...")
        self._set_progress(45)

        schijf = self._zoek_pico_schijf()
        if not schijf:
            self._log("RPI-RP2 schijf niet gevonden.", "err")
            self._log("→ Houd BOOTSEL ingedrukt terwijl je de Pico aansluit,", "dim")
            self._log("  klik daarna opnieuw op 'Installeer'.", "dim")
            return

        self._log(f"Pico-schijf gevonden: {schijf}")
        doel = os.path.join(schijf, os.path.basename(firmware_pad))
        try:
            shutil.copy2(firmware_pad, doel)
            self._log("✅ Pico W flash geslaagd! Herstart automatisch.", "ok")
            self._set_progress(100)
        except PermissionError:
            self._log("Kopieerfout: start de installer als administrator.", "err")
        except Exception as e:
            self._log(f"Kopiëren mislukt: {e}", "err")

    def _zoek_pico_schijf(self):
        if sys.platform != "win32":
            # Linux/Mac: zoek gemount volume
            for base in ["/media", "/Volumes", "/mnt"]:
                if not os.path.isdir(base):
                    continue
                for entry in os.listdir(base):
                    info = os.path.join(base, entry, "INFO_UF2.TXT")
                    if os.path.exists(info):
                        try:
                            if "RP2040" in open(info).read():
                                return os.path.join(base, entry)
                        except Exception:
                            pass
            return None

        # Windows: loop over alle schijfletters
        bitmask = ctypes.windll.kernel32.GetLogicalDrives()
        for letter in string.ascii_uppercase:
            if not (bitmask & 1):
                bitmask >>= 1
                continue
            bitmask >>= 1
            drive = f"{letter}:\\"
            info = os.path.join(drive, "INFO_UF2.TXT")
            if os.path.exists(info):
                try:
                    if "RP2040" in open(info).read():
                        return drive
                except Exception:
                    pass
        return None

    # ─── Subprocess helper ────────────────────────────────────────────────

    def _run_subprocess(self, cmd, pct_start, pct_range) -> bool:
        """Start subprocess, log uitvoer, geeft True terug bij succes."""
        pw = self._var_ota_pw.get()
        log_cmd = [("***" if a == pw and a else a) for a in cmd]
        self._log(f"$ {' '.join(log_cmd)}", "dim")
        try:
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                text=True, bufsize=1
            )
            laatste_lijn = ""
            for lijn in proc.stdout:
                lijn = lijn.rstrip()
                if not lijn:
                    continue
                laatste_lijn = lijn
                if any(w in lijn.lower() for w in ("error", "failed", "auth", "denied", "busy")):
                    tag = "err"
                elif any(w in lijn.lower() for w in ("writing", "uploading", "%")):
                    tag = "hl"
                else:
                    tag = ""
                self._log(lijn, tag)
                m = re.search(r'(\d+)\s*%', lijn)
                if m:
                    pct = pct_start + int(m.group(1)) * pct_range // 100
                    self._set_progress(pct)
            proc.wait()
            if proc.returncode == 0:
                self._log("✅ Geslaagd!", "ok")
                self._set_progress(100)
                return True
            else:
                self._log(f"✗ Fout (exitcode {proc.returncode})", "err")
                ll = laatste_lijn.lower()
                if "auth" in ll:
                    self._log("→ Controleer het OTA-wachtwoord.", "err")
                elif "busy" in ll or "permission" in ll or "toegang" in ll:
                    self._log("→ Poort bezet — sluit Arduino IDE / wacht 5 s en probeer opnieuw.", "err")
                return False
        except FileNotFoundError:
            self._log(f"Commando niet gevonden: {cmd[0]}", "err")
            return False
        except Exception as e:
            self._log(f"Subprocess fout: {e}", "err")
            return False

    # ─── UI helpers ───────────────────────────────────────────────────────

    def _log(self, tekst: str, tag: str = ""):
        def _do():
            self._log_widget.config(state="normal")
            ts = time.strftime("%H:%M:%S")
            if tag:
                self._log_widget.insert("end", f"[{ts}] {tekst}\n", tag)
            else:
                self._log_widget.insert("end", f"[{ts}] {tekst}\n")
            self._log_widget.see("end")
            self._log_widget.config(state="disabled")
        self.after(0, _do)

    def _log_wissen(self):
        self._log_widget.config(state="normal")
        self._log_widget.delete("1.0", "end")
        self._log_widget.config(state="disabled")

    def _set_status(self, tekst: str):
        self.after(0, lambda: self._var_status.set(tekst))

    def _set_progress(self, pct: int):
        self.after(0, lambda: self._progressbar.config(value=pct))

    def _bundle_pad(self, relatief: str) -> str:
        """Pad naar bundled bestand (werkt in .exe via _MEIPASS en in dev)."""
        if getattr(sys, "frozen", False):
            base = sys._MEIPASS
        else:
            base = os.path.dirname(os.path.abspath(__file__))
        return os.path.join(base, relatief)

    def _laad_header_logo(self):
        try:
            return tk.PhotoImage(data=HEADER_LOGO_B64)
        except Exception:
            return None

    def _stel_min_hoogte_in(self):
        self.update_idletasks()
        # Hardcoded minimum: header(64) + streep(3) + footer(56) + content(489)
        self.minsize(640, 612)

    def on_close(self):
        if self._zconf:
            try:
                self._zconf.close()
            except Exception:
                pass
        self.destroy()


# ─── mDNS listener ────────────────────────────────────────────────────────

if MDNS_OK:
    class _MdnsListener(ServiceListener):
        def __init__(self, app: BkosInstaller):
            self._app = app

        def add_service(self, zc: "Zeroconf", type_: str, name: str):
            info = zc.get_service_info(type_, name)
            if info and info.addresses:
                host = info.server.rstrip(".")
                ip   = socket.inet_ntoa(info.addresses[0])
                self._app._wifi_devices[host] = ip
                self._app.after(0, self._app._ververs_wifi_lijst)

        def update_service(self, zc, type_, name):
            self.add_service(zc, type_, name)

        def remove_service(self, zc, type_, name):
            host = name.split(".")[0] + ".local"
            self._app._wifi_devices.pop(host, None)
            self._app.after(0, self._app._ververs_wifi_lijst)
else:
    class _MdnsListener:
        def __init__(self, app): pass


# ─── esptool stdout capture ───────────────────────────────────────────────

class _EsptoolCapture:
    """Vangt esptool stdout op en stuurt het naar de log."""
    def __init__(self, app: BkosInstaller, voortgang_cb):
        self._app = app
        self._voortgang_cb = voortgang_cb
        self._buf = ""

    def write(self, tekst: str):
        self._buf += tekst
        while "\n" in self._buf:
            lijn, self._buf = self._buf.split("\n", 1)
            lijn = lijn.strip()
            if lijn:
                self._app._log(lijn)
            m = re.search(r'(\d+)\s*%', lijn)
            if m:
                self._voortgang_cb(int(m.group(1)))

    def flush(self):
        pass

    def fileno(self):
        raise io.UnsupportedOperation("fileno")


# ─── Entry point ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = BkosInstaller()
    app.protocol("WM_DELETE_WINDOW", app.on_close)
    app.mainloop()

